/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#loader contenttweaker 

#priority 2201
#no_fix_recipe_book

import crafttweaker.liquid.ILiquidStack;
import crafttweaker.game.IGame;

import mods.contenttweaker.tconstruct.Material;
import mods.contenttweaker.tconstruct.MaterialBuilder;
import mods.contenttweaker.Fluid;
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Color;

val molten_fusion_matrix = mods.contenttweaker.VanillaFactory.createFluid("fusion_matrix", Color.fromHex("4a148c").getIntColor());
molten_fusion_matrix.material = <blockmaterial:lava>;
molten_fusion_matrix.viscosity = 2000;
molten_fusion_matrix.density = 4000;
molten_fusion_matrix.rarity = "EPIC";
molten_fusion_matrix.colorize = true;
molten_fusion_matrix.temperature = 2800;
molten_fusion_matrix.luminosity = 15;
molten_fusion_matrix.color = Color.fromHex("4a148c").getIntColor();
molten_fusion_matrix.stillLocation = "base:fluids/molten";
molten_fusion_matrix.flowingLocation = "base:fluids/molten_flowing";
molten_fusion_matrix.register();

val molten_insanium = mods.contenttweaker.VanillaFactory.createFluid("insanium", Color.fromHex("aa00ff").getIntColor());
molten_insanium.material = <blockmaterial:lava>;
molten_insanium.viscosity = 2000;
molten_insanium.density = 2000;
molten_insanium.rarity = "EPIC";
molten_insanium.colorize = true;
molten_insanium.luminosity = 10;
molten_insanium.temperature = 1800;
molten_insanium.color = Color.fromHex("aa00ff").getIntColor();
molten_insanium.stillLocation = "base:fluids/molten";
molten_insanium.flowingLocation = "base:fluids/molten_flowing";
molten_insanium.register();

val molten_ethaxium = mods.contenttweaker.VanillaFactory.createFluid("ethaxium", Color.fromHex("5f7570").getIntColor());
molten_ethaxium.material = <blockmaterial:lava>;
molten_ethaxium.viscosity = 2400;
molten_ethaxium.density = 5400;
molten_ethaxium.rarity = "EPIC";
molten_ethaxium.colorize = true;
molten_ethaxium.temperature = 2000;
molten_ethaxium.luminosity = 10;
molten_ethaxium.color = Color.fromHex("5f7570").getIntColor();
molten_ethaxium.stillLocation = "base:fluids/molten";
molten_ethaxium.flowingLocation = "base:fluids/molten_flowing";
molten_ethaxium.register();

val molten_mithrillium = mods.contenttweaker.VanillaFactory.createFluid("mithrillium", Color.fromHex("2979ff").getIntColor());
molten_mithrillium.material = <blockmaterial:lava>;
molten_mithrillium.viscosity = 2400;
molten_mithrillium.density = 2400;
molten_mithrillium.rarity = "EPIC";
molten_mithrillium.colorize = true;
molten_mithrillium.temperature = 900;
molten_mithrillium.luminosity = 10;
molten_mithrillium.color = Color.fromHex("2979ff").getIntColor();
molten_mithrillium.stillLocation = "base:fluids/molten";
molten_mithrillium.flowingLocation = "base:fluids/molten_flowing";
molten_mithrillium.register();

val molten_adaminite = mods.contenttweaker.VanillaFactory.createFluid("adaminite", Color.fromHex("ff1744").getIntColor());
molten_adaminite.material = <blockmaterial:lava>;
molten_adaminite.viscosity = 2400;
molten_adaminite.density = 2400;
molten_adaminite.rarity = "EPIC";
molten_adaminite.colorize = true;
molten_adaminite.temperature = 1000;
molten_adaminite.luminosity = 10;
molten_adaminite.color = Color.fromHex("ff1744").getIntColor();
molten_adaminite.stillLocation = "base:fluids/molten";
molten_adaminite.flowingLocation = "base:fluids/molten_flowing";
molten_adaminite.register();

val molten_mithminite = mods.contenttweaker.VanillaFactory.createFluid("mithminite", Color.fromHex("ff4081").getIntColor());
molten_mithminite.material = <blockmaterial:lava>;
molten_mithminite.viscosity = 2400;
molten_mithminite.rarity = "EPIC";
molten_mithminite.colorize = true;
molten_mithminite.temperature = 1200;
molten_mithminite.luminosity = 10;
molten_mithminite.color = Color.fromHex("ff4081").getIntColor();
molten_mithminite.stillLocation = "base:fluids/molten";
molten_mithminite.flowingLocation = "base:fluids/molten_flowing";
molten_mithminite.register();

val molten_ravaging = mods.contenttweaker.VanillaFactory.createFluid("ravaging", Color.fromHex("ffc1e3").getIntColor());
molten_ravaging.material = <blockmaterial:lava>;
molten_ravaging.viscosity = 2400;
molten_ravaging.density = 2400;
molten_ravaging.rarity = "EPIC";
molten_ravaging.colorize = true;
molten_ravaging.temperature = 1600;
molten_ravaging.luminosity = 10;
molten_ravaging.color = Color.fromHex("ffc1e3").getIntColor();
molten_ravaging.stillLocation = "base:fluids/molten";
molten_ravaging.flowingLocation = "base:fluids/molten_flowing";
molten_ravaging.register();

val molten_gaia = mods.contenttweaker.VanillaFactory.createFluid("gaia", Color.fromHex("ff80ab").getIntColor());
molten_gaia.material = <blockmaterial:lava>;
molten_gaia.viscosity = 2400;
molten_gaia.rarity = "EPIC";
molten_gaia.colorize = true;
molten_gaia.temperature = 1400;
molten_gaia.luminosity = 10;
molten_gaia.color = Color.fromHex("ff80ab").getIntColor();
molten_gaia.stillLocation = "base:fluids/molten";
molten_gaia.flowingLocation = "base:fluids/molten_flowing";
molten_gaia.register();

val molten_terra_alloy = mods.contenttweaker.VanillaFactory.createFluid("terra_alloy", Color.fromHex("70cf7b").getIntColor());
molten_terra_alloy.material = <blockmaterial:lava>;
molten_terra_alloy.viscosity = 2400;
molten_terra_alloy.density = 2400;
molten_terra_alloy.rarity = "EPIC";
molten_terra_alloy.colorize = true;
molten_terra_alloy.temperature = 2500;
molten_terra_alloy.luminosity = 12;
molten_terra_alloy.color = Color.fromHex("70cf7b").getIntColor();
molten_terra_alloy.stillLocation = "base:fluids/molten";
molten_terra_alloy.flowingLocation = "base:fluids/molten_flowing";
molten_terra_alloy.register();

val molten_cosmilite = mods.contenttweaker.VanillaFactory.createFluid("cosmilite", Color.fromHex("ff416c").getIntColor());
molten_cosmilite.material = <blockmaterial:lava>;
molten_cosmilite.viscosity = 100;
molten_cosmilite.density = 5000000;
molten_cosmilite.rarity = "EPIC";
molten_cosmilite.colorize = true;
molten_cosmilite.temperature = 32000;
molten_cosmilite.luminosity = 15;
molten_cosmilite.color = Color.fromHex("ff416c").getIntColor();
molten_cosmilite.stillLocation = "base:fluids/molten";
molten_cosmilite.flowingLocation = "base:fluids/molten_flowing";
molten_cosmilite.register();

val molten_astral_metal = mods.contenttweaker.VanillaFactory.createFluid("astral_metal", Color.fromHex("d500f9").getIntColor());
molten_astral_metal.material = <blockmaterial:lava>;
molten_astral_metal.viscosity = 2400;
molten_astral_metal.density = 10000;
molten_astral_metal.rarity = "EPIC";
molten_astral_metal.colorize = true;
molten_astral_metal.temperature = 12000;
molten_astral_metal.luminosity = 15;
molten_astral_metal.color = Color.fromHex("d500f9").getIntColor();
molten_astral_metal.stillLocation = "base:fluids/molten";
molten_astral_metal.flowingLocation = "base:fluids/molten_flowing";
molten_astral_metal.register();

val molten_orichalcos = mods.contenttweaker.VanillaFactory.createFluid("orichalcos", Color.fromHex("ec407a").getIntColor());
molten_orichalcos.material = <blockmaterial:lava>;
molten_orichalcos.viscosity = 2600;
molten_orichalcos.density = 12000;
molten_orichalcos.rarity = "EPIC";
molten_orichalcos.colorize = true;
molten_orichalcos.temperature = 12000;
molten_orichalcos.luminosity = 15;
molten_orichalcos.color = Color.fromHex("ec407a").getIntColor();
molten_orichalcos.stillLocation = "base:fluids/molten";
molten_orichalcos.flowingLocation = "base:fluids/molten_flowing";
molten_orichalcos.register();

val molten_ancient_debris = mods.contenttweaker.VanillaFactory.createFluid("ancient_debris", Color.fromHex("8d6e63").getIntColor());
molten_ancient_debris.material = <blockmaterial:lava>;
molten_ancient_debris.viscosity = 24000;
molten_ancient_debris.density = 100000;
molten_ancient_debris.rarity = "EPIC";
molten_ancient_debris.colorize = true;
molten_ancient_debris.temperature = 1520;
molten_ancient_debris.luminosity = 15;
molten_ancient_debris.color = Color.fromHex("8d6e63").getIntColor();
molten_ancient_debris.stillLocation = "base:fluids/molten";
molten_ancient_debris.flowingLocation = "base:fluids/molten_flowing";
molten_ancient_debris.register();

val molten_netherite = mods.contenttweaker.VanillaFactory.createFluid("netherite", Color.fromHex("42403f").getIntColor());
molten_netherite.material = <blockmaterial:lava>;
molten_netherite.viscosity = 24000;
molten_netherite.density = 100000;
molten_netherite.rarity = "EPIC";
molten_netherite.colorize = true;
molten_netherite.temperature = 1800;
molten_netherite.luminosity = 15;
molten_netherite.color = Color.fromHex("42403f").getIntColor();
molten_netherite.stillLocation = "base:fluids/molten";
molten_netherite.flowingLocation = "base:fluids/molten_flowing";
molten_netherite.register();

val molten_scorched = mods.contenttweaker.VanillaFactory.createFluid("scorched", Color.fromHex("514623").getIntColor());
molten_scorched.material = <blockmaterial:lava>;
molten_scorched.viscosity = 2400;
molten_scorched.density = 10000;
molten_scorched.rarity = "EPIC";
molten_scorched.colorize = true;
molten_scorched.temperature = 1350;
molten_scorched.luminosity = 15;
molten_scorched.color = Color.fromHex("514623").getIntColor();
molten_scorched.stillLocation = "base:fluids/molten";
molten_scorched.flowingLocation = "base:fluids/molten_flowing";
molten_scorched.register();

val organic_fluid = mods.contenttweaker.VanillaFactory.createFluid("organic_fluid", Color.fromHex("cddc39").getIntColor());
organic_fluid.material = <blockmaterial:water>;
organic_fluid.viscosity = 5000;
organic_fluid.density = 12000;
organic_fluid.rarity = "EPIC";
organic_fluid.colorize = true;
organic_fluid.temperature = 257;
organic_fluid.luminosity = 5;
organic_fluid.color = Color.fromHex("cddc39").getIntColor();
organic_fluid.register();

val molten_modularium = mods.contenttweaker.VanillaFactory.createFluid("modularium", Color.fromHex("ff5722").getIntColor());
molten_modularium.material = <blockmaterial:lava>;
molten_modularium.viscosity = 2400;
molten_modularium.density = 10000;
molten_modularium.colorize = true;
molten_modularium.temperature = 1600;
molten_modularium.luminosity = 15;
molten_modularium.color = Color.fromHex("ff5722").getIntColor();
molten_modularium.stillLocation = "base:fluids/molten";
molten_modularium.flowingLocation = "base:fluids/molten_flowing";
molten_modularium.register();

val molten_meteor = mods.contenttweaker.VanillaFactory.createFluid("meteor", Color.fromHex("c62828").getIntColor());
molten_meteor.material = <blockmaterial:lava>;
molten_meteor.viscosity = 2400;
molten_meteor.density = 10000;
molten_meteor.colorize = true;
molten_meteor.temperature = 1400;
molten_meteor.luminosity = 15;
molten_meteor.color = Color.fromHex("c62828").getIntColor();
molten_meteor.stillLocation = "base:fluids/molten";
molten_meteor.flowingLocation = "base:fluids/molten_flowing";
molten_meteor.register();

val molten_stainless_steel = mods.contenttweaker.VanillaFactory.createFluid("stainless_steel", Color.fromHex("757575").getIntColor());
molten_stainless_steel.material = <blockmaterial:lava>;
molten_stainless_steel.viscosity = 2400;
molten_stainless_steel.density = 12000;
molten_stainless_steel.colorize = true;
molten_stainless_steel.temperature = 1450;
molten_stainless_steel.luminosity = 15;
molten_stainless_steel.color = Color.fromHex("757575").getIntColor();
molten_stainless_steel.stillLocation = "base:fluids/molten";
molten_stainless_steel.flowingLocation = "base:fluids/molten_flowing";
molten_stainless_steel.register();

val molten_protonium = mods.contenttweaker.VanillaFactory.createFluid("protonium", Color.fromHex("f240b7").getIntColor());
molten_protonium.material = <blockmaterial:lava>;
molten_protonium.viscosity = 16384;
molten_protonium.density = 2147483647;
molten_protonium.rarity = "EPIC";
molten_protonium.colorize = true;
molten_protonium.temperature = 32767;
molten_protonium.luminosity = 15;
molten_protonium.color = Color.fromHex("f240b7").getIntColor();
molten_protonium.stillLocation = "base:fluids/molten";
molten_protonium.flowingLocation = "base:fluids/molten_flowing";
molten_protonium.register();

val molten_electronium = mods.contenttweaker.VanillaFactory.createFluid("electronium", Color.fromHex("434eb5").getIntColor());
molten_electronium.material = <blockmaterial:lava>;
molten_electronium.viscosity = 32767;
molten_electronium.density = 32767;
molten_electronium.rarity = "EPIC";
molten_electronium.colorize = true;
molten_electronium.temperature = 16384;
molten_electronium.luminosity = 15;
molten_electronium.color = Color.fromHex("434eb5").getIntColor();
molten_electronium.stillLocation = "base:fluids/molten";
molten_electronium.flowingLocation = "base:fluids/molten_flowing";
molten_electronium.register();

val molten_crimsonite = mods.contenttweaker.VanillaFactory.createFluid("crimsonite", Color.fromHex("a30000").getIntColor());
molten_crimsonite.material = <blockmaterial:lava>;
molten_crimsonite.viscosity = 3000;
molten_crimsonite.density = 4500;
molten_crimsonite.rarity = "EPIC";
molten_crimsonite.colorize = true;
molten_crimsonite.temperature = 1550;
molten_crimsonite.luminosity = 12;
molten_crimsonite.color = Color.fromHex("a30000").getIntColor();
molten_crimsonite.stillLocation = "base:fluids/molten";
molten_crimsonite.flowingLocation = "base:fluids/molten_flowing";
molten_crimsonite.register();

val molten_manganese_steel = mods.contenttweaker.VanillaFactory.createFluid("manganese_steel", Color.fromHex("455a64").getIntColor());
molten_manganese_steel.material = <blockmaterial:lava>;
molten_manganese_steel.viscosity = 3000;
molten_manganese_steel.density = 6500;
molten_manganese_steel.colorize = true;
molten_manganese_steel.temperature = 900;
molten_manganese_steel.luminosity = 10;
molten_manganese_steel.color = Color.fromHex("455a64").getIntColor();
molten_manganese_steel.stillLocation = "base:fluids/molten";
molten_manganese_steel.flowingLocation = "base:fluids/molten_flowing";
molten_manganese_steel.register();

val molten_durasteel = mods.contenttweaker.VanillaFactory.createFluid("durasteel", Color.fromHex("303f9f").getIntColor());
molten_durasteel.material = <blockmaterial:lava>;
molten_durasteel.viscosity = 3000;
molten_durasteel.density = 6500;
molten_durasteel.colorize = true;
molten_durasteel.temperature = 1200;
molten_durasteel.luminosity = 10;
molten_durasteel.color = Color.fromHex("006064").getIntColor();
molten_durasteel.stillLocation = "base:fluids/molten";
molten_durasteel.flowingLocation = "base:fluids/molten_flowing";
molten_durasteel.register();

val molten_aeonsteel = mods.contenttweaker.VanillaFactory.createFluid("aeonsteel", Color.fromHex("006064").getIntColor());
molten_aeonsteel.material = <blockmaterial:lava>;
molten_aeonsteel.viscosity = 3000;
molten_aeonsteel.density = 6500;
molten_aeonsteel.colorize = true;
molten_aeonsteel.temperature = 1300;
molten_aeonsteel.luminosity = 10;
molten_aeonsteel.color = Color.fromHex("455a64").getIntColor();
molten_aeonsteel.stillLocation = "base:fluids/molten";
molten_aeonsteel.flowingLocation = "base:fluids/molten_flowing";
molten_aeonsteel.register();

val molten_chromasteel = mods.contenttweaker.VanillaFactory.createFluid("chromasteel", Color.fromHex("f44336").getIntColor());
molten_chromasteel.material = <blockmaterial:lava>;
molten_chromasteel.viscosity = 3000;
molten_chromasteel.density = 6500;
molten_chromasteel.colorize = true;
molten_chromasteel.temperature = 1400;
molten_chromasteel.luminosity = 10;
molten_chromasteel.color = Color.fromHex("f44336").getIntColor();
molten_chromasteel.stillLocation = "base:fluids/molten";
molten_chromasteel.flowingLocation = "base:fluids/molten_flowing";
molten_chromasteel.register();

val molten_spectre = mods.contenttweaker.VanillaFactory.createFluid("spectre", Color.fromHex("90a4ae").getIntColor());
molten_spectre.material = <blockmaterial:lava>;
molten_spectre.viscosity = 3000;
molten_spectre.density = 6500;
molten_spectre.colorize = true;
molten_spectre.temperature = 400;
molten_spectre.luminosity = 10;
molten_spectre.color = Color.fromHex("90a4ae").getIntColor();
molten_spectre.stillLocation = "base:fluids/molten";
molten_spectre.flowingLocation = "base:fluids/molten_flowing";
molten_spectre.register();

val molten_gaiasteel = mods.contenttweaker.VanillaFactory.createFluid("gaiasteel", Color.fromHex("f44336").getIntColor());
molten_gaiasteel.material = <blockmaterial:lava>;
molten_gaiasteel.viscosity = 3000;
molten_gaiasteel.density = 6500;
molten_gaiasteel.colorize = true;
molten_gaiasteel.temperature = 1000;
molten_gaiasteel.luminosity = 10;
molten_gaiasteel.color = Color.fromHex("f44336").getIntColor();
molten_gaiasteel.stillLocation = "base:fluids/molten";
molten_gaiasteel.flowingLocation = "base:fluids/molten_flowing";
molten_gaiasteel.register();

val molten_blackiron = mods.contenttweaker.VanillaFactory.createFluid("blackiron", Color.fromHex("000000").getIntColor());
molten_blackiron.material = <blockmaterial:lava>;
molten_blackiron.viscosity = 3000;
molten_blackiron.density = 6500;
molten_blackiron.colorize = true;
molten_blackiron.temperature = 1000;
molten_blackiron.luminosity = 10;
molten_blackiron.color = Color.fromHex("000000").getIntColor();
molten_blackiron.stillLocation = "base:fluids/molten";
molten_blackiron.flowingLocation = "base:fluids/molten_flowing";
molten_blackiron.register();

val molten_heavenite = mods.contenttweaker.VanillaFactory.createFluid("heavenite", Color.fromHex("00ffff").getIntColor()); 
molten_heavenite.material = <blockmaterial:lava>;
molten_heavenite.viscosity = 3000;
molten_heavenite.density = 6500;
molten_heavenite.colorize = true;
molten_heavenite.temperature = 1000;
molten_heavenite.luminosity = 10;
molten_heavenite.color = Color.fromHex("00ffff").getIntColor();
molten_heavenite.stillLocation = "base:fluids/molten";
molten_heavenite.flowingLocation = "base:fluids/molten_flowing";
molten_heavenite.register();

val molten_ghostite = mods.contenttweaker.VanillaFactory.createFluid("ghostite", Color.fromHex("321463").getIntColor()); 
molten_ghostite.material = <blockmaterial:lava>;
molten_ghostite.viscosity = 3000;
molten_ghostite.density = 6500;
molten_ghostite.colorize = true;
molten_ghostite.temperature = 1000;
molten_ghostite.luminosity = 10;
molten_ghostite.color = Color.fromHex("321463").getIntColor();
molten_ghostite.stillLocation = "base:fluids/molten";
molten_ghostite.flowingLocation = "base:fluids/molten_flowing";
molten_ghostite.register();

val molten_waringlium = mods.contenttweaker.VanillaFactory.createFluid("waringlium", Color.fromHex("3e6599").getIntColor()); 
molten_waringlium.material = <blockmaterial:lava>;
molten_waringlium.viscosity = 3000;
molten_waringlium.density = 6500;
molten_waringlium.colorize = true;
molten_waringlium.temperature = 1000;
molten_waringlium.luminosity = 10;
molten_waringlium.color = Color.fromHex("3e6599").getIntColor();
molten_waringlium.stillLocation = "base:fluids/molten";
molten_waringlium.flowingLocation = "base:fluids/molten_flowing";
molten_waringlium.register();

val molten_tierite = mods.contenttweaker.VanillaFactory.createFluid("tierite", Color.fromHex("6296ad").getIntColor()); 
molten_tierite.material = <blockmaterial:lava>;
molten_tierite.viscosity = 3000;
molten_tierite.density = 6500;
molten_tierite.colorize = true;
molten_tierite.temperature = 1000;
molten_tierite.luminosity = 10;
molten_tierite.color = Color.fromHex("6296ad").getIntColor();
molten_tierite.stillLocation = "base:fluids/molten";
molten_tierite.flowingLocation = "base:fluids/molten_flowing";
molten_tierite.register();

val molten_cheatieum = mods.contenttweaker.VanillaFactory.createFluid("cheatieum", Color.fromHex("bfbfbf").getIntColor()); 
molten_cheatieum.material = <blockmaterial:lava>;
molten_cheatieum.viscosity = 3000;
molten_cheatieum.density = 6500;
molten_cheatieum.colorize = true;
molten_cheatieum.temperature = 1000;
molten_cheatieum.luminosity = 10;
molten_cheatieum.color = Color.fromHex("bfbfbf").getIntColor();
molten_cheatieum.stillLocation = "base:fluids/molten";
molten_cheatieum.flowingLocation = "base:fluids/molten_flowing";
molten_cheatieum.register();

val molten_idiessite = mods.contenttweaker.VanillaFactory.createFluid("idiessite", Color.fromHex("b7cdf9").getIntColor());
molten_idiessite.material = <blockmaterial:lava>; 
molten_idiessite.viscosity = 3000;
molten_idiessite.density = 6500;
molten_idiessite.colorize = true;
molten_idiessite.temperature = 1000;
molten_idiessite.luminosity = 10;
molten_idiessite.color = Color.fromHex("b7cdf9").getIntColor();
molten_idiessite.stillLocation = "base:fluids/molten";
molten_idiessite.flowingLocation = "base:fluids/molten_flowing";
molten_idiessite.register();

val molten_cthughate = mods.contenttweaker.VanillaFactory.createFluid("cthughate", Color.fromHex("c2003d").getIntColor()); 
molten_cthughate.material = <blockmaterial:lava>;
molten_cthughate.viscosity = 3000;
molten_cthughate.density = 6500;
molten_cthughate.colorize = true;
molten_cthughate.temperature = 8000;
molten_cthughate.luminosity = 10;
molten_cthughate.color = Color.fromHex("c2003d").getIntColor();
molten_cthughate.stillLocation = "base:fluids/molten";
molten_cthughate.flowingLocation = "base:fluids/molten_flowing";
molten_cthughate.register();

val molten_ranglium = mods.contenttweaker.VanillaFactory.createFluid("ranglium", Color.fromHex("7f7f7f").getIntColor()); 
molten_ranglium.material = <blockmaterial:lava>;
molten_ranglium.viscosity = 3000;
molten_ranglium.density = 6500;
molten_ranglium.colorize = true;
molten_ranglium.temperature = 1000;
molten_ranglium.luminosity = 10;
molten_ranglium.color = Color.fromHex("7f7f7f").getIntColor();
molten_ranglium.stillLocation = "base:fluids/molten";
molten_ranglium.flowingLocation = "base:fluids/molten_flowing";
molten_ranglium.register();

val molten_godiarite = mods.contenttweaker.VanillaFactory.createFluid("godiarite", Color.fromHex("96500c").getIntColor()); 
molten_godiarite.material = <blockmaterial:lava>;
molten_godiarite.viscosity = 3000;
molten_godiarite.density = 6500;
molten_godiarite.colorize = true;
molten_godiarite.temperature = 1000;
molten_godiarite.luminosity = 10;
molten_godiarite.color = Color.fromHex("96500c").getIntColor();
molten_godiarite.stillLocation = "base:fluids/molten";
molten_godiarite.flowingLocation = "base:fluids/molten_flowing";
molten_godiarite.register();

val molten_rainite = mods.contenttweaker.VanillaFactory.createFluid("rainite", Color.fromHex("000079").getIntColor()); 
molten_rainite.material = <blockmaterial:lava>;
molten_rainite.viscosity = 3000;
molten_rainite.density = 6500;
molten_rainite.colorize = true;
molten_rainite.temperature = 1000;
molten_rainite.luminosity = 10;
molten_rainite.color = Color.fromHex("000079").getIntColor();
molten_rainite.stillLocation = "base:fluids/molten";
molten_rainite.flowingLocation = "base:fluids/molten_flowing";
molten_rainite.register();

val molten_panloeseum = mods.contenttweaker.VanillaFactory.createFluid("panloeseum", Color.fromHex("00d18a").getIntColor()); 
molten_panloeseum.material = <blockmaterial:lava>;
molten_panloeseum.viscosity = 3000;
molten_panloeseum.density = 6500;
molten_panloeseum.colorize = true;
molten_panloeseum.temperature = 1000;
molten_panloeseum.luminosity = 10;
molten_panloeseum.color = Color.fromHex("00d18a").getIntColor();
molten_panloeseum.stillLocation = "base:fluids/molten";
molten_panloeseum.flowingLocation = "base:fluids/molten_flowing";
molten_panloeseum.register();

val molten_husturite = mods.contenttweaker.VanillaFactory.createFluid("husturite", Color.fromHex("de980d").getIntColor()); 
molten_husturite.material = <blockmaterial:lava>;
molten_husturite.viscosity = 3000;
molten_husturite.density = 6500;
molten_husturite.colorize = true;
molten_husturite.temperature = 1000;
molten_husturite.luminosity = 10;
molten_husturite.color = Color.fromHex("de980d").getIntColor();
molten_husturite.stillLocation = "base:fluids/molten";
molten_husturite.flowingLocation = "base:fluids/molten_flowing";
molten_husturite.register();

val molten_fallenium = mods.contenttweaker.VanillaFactory.createFluid("fallenium", Color.fromHex("890000").getIntColor()); 
molten_fallenium.material = <blockmaterial:lava>;
molten_fallenium.viscosity = 3000;
molten_fallenium.density = 6500;
molten_fallenium.colorize = true;
molten_fallenium.temperature = 1000;
molten_fallenium.luminosity = 10;
molten_fallenium.color = Color.fromHex("890000").getIntColor();
molten_fallenium.stillLocation = "base:fluids/molten";
molten_fallenium.flowingLocation = "base:fluids/molten_flowing";
molten_fallenium.register();

val molten_phoenixite = mods.contenttweaker.VanillaFactory.createFluid("phoenixite", Color.fromHex("f26522").getIntColor()); 
molten_phoenixite.material = <blockmaterial:lava>;
molten_phoenixite.viscosity = 3000;
molten_phoenixite.density = 6500;
molten_phoenixite.colorize = true;
molten_phoenixite.temperature = 1000;
molten_phoenixite.luminosity = 10;
molten_phoenixite.color = Color.fromHex("f26522").getIntColor();
molten_phoenixite.stillLocation = "base:fluids/molten";
molten_phoenixite.flowingLocation = "base:fluids/molten_flowing";
molten_phoenixite.register();

val molten_depthite = mods.contenttweaker.VanillaFactory.createFluid("depthite", Color.fromHex("004f00").getIntColor()); 
molten_depthite.material = <blockmaterial:lava>;
molten_depthite.viscosity = 3000;
molten_depthite.density = 6500;
molten_depthite.colorize = true;
molten_depthite.temperature = 1000;
molten_depthite.luminosity = 10;
molten_depthite.color = Color.fromHex("004f00").getIntColor();
molten_depthite.stillLocation = "base:fluids/molten";
molten_depthite.flowingLocation = "base:fluids/molten_flowing";
molten_depthite.register();

val molten_lovaquite = mods.contenttweaker.VanillaFactory.createFluid("lovaquite", Color.fromHex("9dac67").getIntColor()); 
molten_lovaquite.material = <blockmaterial:lava>;
molten_lovaquite.viscosity = 3000;
molten_lovaquite.density = 6500;
molten_lovaquite.colorize = true;
molten_lovaquite.temperature = 1000;
molten_lovaquite.luminosity = 10;
molten_lovaquite.color = Color.fromHex("9dac67").getIntColor();
molten_lovaquite.stillLocation = "base:fluids/molten";
molten_lovaquite.flowingLocation = "base:fluids/molten_flowing";
molten_lovaquite.register();

val molten_rangolarite = mods.contenttweaker.VanillaFactory.createFluid("rangolarite", Color.fromHex("ea0a0e").getIntColor()); 
molten_rangolarite.material = <blockmaterial:lava>;
molten_rangolarite.viscosity = 3000;
molten_rangolarite.density = 6500;
molten_rangolarite.colorize = true;
molten_rangolarite.temperature = 1000;
molten_rangolarite.luminosity = 10;
molten_rangolarite.color = Color.fromHex("ea0a0e").getIntColor();
molten_rangolarite.stillLocation = "base:fluids/molten";
molten_rangolarite.flowingLocation = "base:fluids/molten_flowing";
molten_rangolarite.register();

val molten_clearite = mods.contenttweaker.VanillaFactory.createFluid("clearite", Color.fromHex("8affff").getIntColor()); 
molten_clearite.material = <blockmaterial:lava>;
molten_clearite.viscosity = 3000;
molten_clearite.density = 6500;
molten_clearite.colorize = true;
molten_clearite.temperature = 1000;
molten_clearite.luminosity = 10;
molten_clearite.color = Color.fromHex("8affff").getIntColor();
molten_clearite.stillLocation = "base:fluids/molten";
molten_clearite.flowingLocation = "base:fluids/molten_flowing";
molten_clearite.register();

val molten_wefenium = mods.contenttweaker.VanillaFactory.createFluid("wefenium", Color.fromHex("f86cad").getIntColor()); 
molten_wefenium.material = <blockmaterial:lava>;
molten_wefenium.viscosity = 3000;
molten_wefenium.density = 6500;
molten_wefenium.colorize = true;
molten_wefenium.temperature = 1000;
molten_wefenium.luminosity = 10;
molten_wefenium.color = Color.fromHex("f86cad").getIntColor();
molten_wefenium.stillLocation = "base:fluids/molten";
molten_wefenium.flowingLocation = "base:fluids/molten_flowing";
molten_wefenium.register();

val molten_errorite = mods.contenttweaker.VanillaFactory.createFluid("errorite", Color.fromHex("141414").getIntColor()); 
molten_errorite.material = <blockmaterial:lava>;
molten_errorite.viscosity = 3000;
molten_errorite.density = 6500;
molten_errorite.colorize = true;
molten_errorite.temperature = 1000;
molten_errorite.luminosity = 10;
molten_errorite.color = Color.fromHex("141414").getIntColor();
molten_errorite.stillLocation = "base:fluids/molten";
molten_errorite.flowingLocation = "base:fluids/molten_flowing";
molten_errorite.register();

val molten_numbereum = mods.contenttweaker.VanillaFactory.createFluid("numbereum", Color.fromHex("2f57a1").getIntColor()); 
molten_numbereum.material = <blockmaterial:lava>;
molten_numbereum.viscosity = 3000;
molten_numbereum.density = 6500;
molten_numbereum.colorize = true;
molten_numbereum.temperature = 1000;
molten_numbereum.luminosity = 10;
molten_numbereum.color = Color.fromHex("2f57a1").getIntColor();
molten_numbereum.stillLocation = "base:fluids/molten";
molten_numbereum.flowingLocation = "base:fluids/molten_flowing";
molten_numbereum.register();

val molten_treasurite = mods.contenttweaker.VanillaFactory.createFluid("treasurite", Color.fromHex("fad2c8").getIntColor()); 
molten_treasurite.material = <blockmaterial:lava>;
molten_treasurite.viscosity = 3000;
molten_treasurite.density = 6500;
molten_treasurite.colorize = true;
molten_treasurite.temperature = 1000;
molten_treasurite.luminosity = 10;
molten_treasurite.color = Color.fromHex("fad2c8").getIntColor();
molten_treasurite.stillLocation = "base:fluids/molten";
molten_treasurite.flowingLocation = "base:fluids/molten_flowing";
molten_treasurite.register();

val molten_leadite = mods.contenttweaker.VanillaFactory.createFluid("leadite", Color.fromHex("8bb1b1").getIntColor()); 
molten_leadite.material = <blockmaterial:lava>;
molten_leadite.viscosity = 3000;
molten_leadite.density = 6500;
molten_leadite.colorize = true;
molten_leadite.temperature = 1000;
molten_leadite.luminosity = 10;
molten_leadite.color = Color.fromHex("8bb1b1").getIntColor();
molten_leadite.stillLocation = "base:fluids/molten";
molten_leadite.flowingLocation = "base:fluids/molten_flowing";
molten_leadite.register();

val molten_martisite = mods.contenttweaker.VanillaFactory.createFluid("martisite", Color.fromHex("f369fa").getIntColor()); 
molten_martisite.material = <blockmaterial:lava>;
molten_martisite.viscosity = 3000;
molten_martisite.density = 6500;
molten_martisite.colorize = true;
molten_martisite.temperature = 1000;
molten_martisite.luminosity = 10;
molten_martisite.color = Color.fromHex("f369fa").getIntColor();
molten_martisite.stillLocation = "base:fluids/molten"; 
molten_martisite.flowingLocation = "base:fluids/molten_flowing";
molten_martisite.register();

val molten_flashite = mods.contenttweaker.VanillaFactory.createFluid("flashite", Color.fromHex("71716d").getIntColor()); 
molten_flashite.material = <blockmaterial:lava>;
molten_flashite.viscosity = 3000;
molten_flashite.density = 6500;
molten_flashite.colorize = true;
molten_flashite.temperature = 1000;
molten_flashite.luminosity = 10;
molten_flashite.color = Color.fromHex("71716d").getIntColor();
molten_flashite.stillLocation = "base:fluids/molten";
molten_flashite.flowingLocation = "base:fluids/molten_flowing";
molten_flashite.register();

val molten_overlaite = mods.contenttweaker.VanillaFactory.createFluid("overlaite", Color.fromHex("480c13").getIntColor()); 
molten_overlaite.material = <blockmaterial:lava>;
molten_overlaite.viscosity = 3000;
molten_overlaite.density = 6500;
molten_overlaite.colorize = true;
molten_overlaite.temperature = 1000;
molten_overlaite.luminosity = 10;
molten_overlaite.color = Color.fromHex("480c13").getIntColor();
molten_overlaite.stillLocation = "base:fluids/molten";
molten_overlaite.flowingLocation = "base:fluids/molten_flowing";
molten_overlaite.register();

val molten_rupee = mods.contenttweaker.VanillaFactory.createFluid("rupee", Color.fromHex("17faff").getIntColor()); 
molten_rupee.material = <blockmaterial:lava>;
molten_rupee.viscosity = 3000;
molten_rupee.density = 6500;
molten_rupee.colorize = true;
molten_rupee.temperature = 1000;
molten_rupee.luminosity = 10;
molten_rupee.color = Color.fromHex("17faff").getIntColor();
molten_rupee.stillLocation = "base:fluids/molten";
molten_rupee.flowingLocation = "base:fluids/molten_flowing";
molten_rupee.register();

val molten_realmite = mods.contenttweaker.VanillaFactory.createFluid("realmite", Color.fromHex("ab6628").getIntColor()); 
molten_realmite.material = <blockmaterial:lava>;
molten_realmite.viscosity = 3000;
molten_realmite.density = 6500;
molten_realmite.colorize = true;
molten_realmite.temperature = 1000;
molten_realmite.luminosity = 10;
molten_realmite.color = Color.fromHex("ab6628").getIntColor();
molten_realmite.stillLocation = "base:fluids/molten";
molten_realmite.flowingLocation = "base:fluids/molten_flowing";
molten_realmite.register();

val molten_arlemite = mods.contenttweaker.VanillaFactory.createFluid("arlemite", Color.fromHex("7ad343").getIntColor()); 
molten_arlemite.material = <blockmaterial:lava>;
molten_arlemite.viscosity = 3000;
molten_arlemite.density = 6500;
molten_arlemite.colorize = true;
molten_arlemite.temperature = 1000;
molten_arlemite.luminosity = 10;
molten_arlemite.color = Color.fromHex("7ad343").getIntColor();
molten_arlemite.stillLocation = "base:fluids/molten"; 
molten_arlemite.flowingLocation = "base:fluids/molten_flowing";
molten_arlemite.register();

val molten_shadow_bar = mods.contenttweaker.VanillaFactory.createFluid("shadow_bar", Color.fromHex("454545").getIntColor()); 
molten_shadow_bar.material = <blockmaterial:lava>;
molten_shadow_bar.viscosity = 3000;
molten_shadow_bar.density = 6500;
molten_shadow_bar.colorize = true;
molten_shadow_bar.temperature = 1000;
molten_shadow_bar.luminosity = 10;
molten_shadow_bar.color = Color.fromHex("454545").getIntColor();
molten_shadow_bar.stillLocation = "base:fluids/molten";
molten_shadow_bar.flowingLocation = "base:fluids/molten_flowing";
molten_shadow_bar.register();

val molten_hellstone = mods.contenttweaker.VanillaFactory.createFluid("hellstone", Color.fromHex("52271d").getIntColor()); 
molten_hellstone.material = <blockmaterial:lava>;
molten_hellstone.viscosity = 3000;
molten_hellstone.density = 6500;
molten_hellstone.colorize = true;
molten_hellstone.temperature = 1000; 
molten_hellstone.luminosity = 10;
molten_hellstone.color = Color.fromHex("52271d").getIntColor();
molten_hellstone.stillLocation = "base:fluids/molten";
molten_hellstone.flowingLocation = "base:fluids/molten_flowing";
molten_hellstone.register();

val molten_lava_solid = mods.contenttweaker.VanillaFactory.createFluid("lava_solid", Color.fromHex("f42421").getIntColor()); 
molten_lava_solid.material = <blockmaterial:lava>;
molten_lava_solid.viscosity = 3000;
molten_lava_solid.density = 6500;
molten_lava_solid.colorize = true;
molten_lava_solid.temperature = 1000;
molten_lava_solid.luminosity = 10;
molten_lava_solid.color = Color.fromHex("f42421").getIntColor();
molten_lava_solid.stillLocation = "base:fluids/molten";
molten_lava_solid.flowingLocation = "base:fluids/molten_flowing";
molten_lava_solid.register();

val molten_balancite = mods.contenttweaker.VanillaFactory.createFluid("balancite", Color.fromHex("01a9ba").getIntColor()); 
molten_balancite.material = <blockmaterial:lava>;
molten_balancite.viscosity = 3000;
molten_balancite.density = 6500;
molten_balancite.colorize = true;
molten_balancite.temperature = 1000;
molten_balancite.luminosity = 10;
molten_balancite.color = Color.fromHex("01a9ba").getIntColor();
molten_balancite.stillLocation = "base:fluids/molten";
molten_balancite.flowingLocation = "base:fluids/molten_flowing";
molten_balancite.register();

val molten_glowing_signalum = mods.contenttweaker.VanillaFactory.createFluid("glowing_signalum", Color.fromHex("b23c16").getIntColor()); 
molten_glowing_signalum.material = <blockmaterial:lava>;
molten_glowing_signalum.viscosity = 3000;
molten_glowing_signalum.density = 6500;
molten_glowing_signalum.colorize = true;
molten_glowing_signalum.temperature = 1000;
molten_glowing_signalum.luminosity = 10;
molten_glowing_signalum.color = Color.fromHex("b23c16").getIntColor();
molten_glowing_signalum.stillLocation = "base:fluids/molten";
molten_glowing_signalum.flowingLocation = "base:fluids/molten_flowing";
molten_glowing_signalum.register();

val molten_fallen_metal = mods.contenttweaker.VanillaFactory.createFluid("fallen_metal", Color.fromHex("680000").getIntColor()); 
molten_fallen_metal.material = <blockmaterial:lava>;
molten_fallen_metal.viscosity = 3000;
molten_fallen_metal.density = 6500;
molten_fallen_metal.colorize = true;
molten_fallen_metal.temperature = 1000;
molten_fallen_metal.luminosity = 10;
molten_fallen_metal.color = Color.fromHex("680000").getIntColor();
molten_fallen_metal.stillLocation = "base:fluids/molten";
molten_fallen_metal.flowingLocation = "base:fluids/molten_flowing";
molten_fallen_metal.register();

val molten_relifed_metal = mods.contenttweaker.VanillaFactory.createFluid("relifed_metal", Color.fromHex("b7ffff").getIntColor()); 
molten_relifed_metal.material = <blockmaterial:lava>;
molten_relifed_metal.viscosity = 3000;
molten_relifed_metal.density = 6500;
molten_relifed_metal.colorize = true;
molten_relifed_metal.temperature = 1000;
molten_relifed_metal.luminosity = 10;
molten_relifed_metal.color = Color.fromHex("b7ffff").getIntColor();
molten_relifed_metal.stillLocation = "base:fluids/molten";
molten_relifed_metal.flowingLocation = "base:fluids/molten_flowing";
molten_relifed_metal.register();

val molten_stormy_metal = mods.contenttweaker.VanillaFactory.createFluid("stormy_metal", Color.fromHex("5c008a").getIntColor()); 
molten_stormy_metal.material = <blockmaterial:lava>;
molten_stormy_metal.viscosity = 3000;
molten_stormy_metal.density = 6500;
molten_stormy_metal.colorize = true;
molten_stormy_metal.temperature = 1000;
molten_stormy_metal.luminosity = 10;
molten_stormy_metal.color = Color.fromHex("5c008a").getIntColor();
molten_stormy_metal.stillLocation = "base:fluids/molten";
molten_stormy_metal.flowingLocation = "base:fluids/molten_flowing";
molten_stormy_metal.register();

val molten_ordered_metal = mods.contenttweaker.VanillaFactory.createFluid("ordered_metal", Color.fromHex("a4a4a4").getIntColor()); 
molten_ordered_metal.material = <blockmaterial:lava>;
molten_ordered_metal.viscosity = 3000;
molten_ordered_metal.density = 6500;
molten_ordered_metal.colorize = true;
molten_ordered_metal.temperature = 1000;
molten_ordered_metal.luminosity = 10;
molten_ordered_metal.color = Color.fromHex("a4a4a4").getIntColor();
molten_ordered_metal.stillLocation = "base:fluids/molten";
molten_ordered_metal.flowingLocation = "base:fluids/molten_flowing";
molten_ordered_metal.register();

val molten_finallium = mods.contenttweaker.VanillaFactory.createFluid("finallium", Color.fromHex("888888").getIntColor()); 
molten_finallium.material = <blockmaterial:lava>;
molten_finallium.viscosity = 3000;
molten_finallium.density = 6500;
molten_finallium.colorize = true;
molten_finallium.temperature = 50000;
molten_finallium.luminosity = 10;
molten_finallium.color = Color.fromHex("888888").getIntColor();
molten_finallium.stillLocation = "base:fluids/molten";
molten_finallium.flowingLocation = "base:fluids/molten_flowing";
molten_finallium.register();

val molten_eden = mods.contenttweaker.VanillaFactory.createFluid("eden", Color.fromHex("a6463c").getIntColor()); 
molten_eden.material = <blockmaterial:lava>;
molten_eden.viscosity = 3000;
molten_eden.density = 6500;
molten_eden.colorize = true;
molten_eden.temperature = 1000;
molten_eden.luminosity = 10;
molten_eden.color = Color.fromHex("a6463c").getIntColor();
molten_eden.stillLocation = "base:fluids/molten";
molten_eden.flowingLocation = "base:fluids/molten_flowing";
molten_eden.register();

val molten_wildwood = mods.contenttweaker.VanillaFactory.createFluid("wildwood", Color.fromHex("2a6f83").getIntColor()); 
molten_wildwood.material = <blockmaterial:lava>;
molten_wildwood.viscosity = 3000;
molten_wildwood.density = 6500;
molten_wildwood.colorize = true;
molten_wildwood.temperature = 1000;
molten_wildwood.luminosity = 10;
molten_wildwood.color = Color.fromHex("2a6f83").getIntColor();
molten_wildwood.stillLocation = "base:fluids/molten";
molten_wildwood.flowingLocation = "base:fluids/molten_flowing";
molten_wildwood.register();

val molten_apalachia = mods.contenttweaker.VanillaFactory.createFluid("apalachia", Color.fromHex("773c95").getIntColor()); 
molten_apalachia.material = <blockmaterial:lava>;
molten_apalachia.viscosity = 3000;
molten_apalachia.density = 6500;
molten_apalachia.colorize = true;
molten_apalachia.temperature = 1000;
molten_apalachia.luminosity = 10;
molten_apalachia.color = Color.fromHex("773c95").getIntColor();
molten_apalachia.stillLocation = "base:fluids/molten";
molten_apalachia.flowingLocation = "base:fluids/molten_flowing";
molten_apalachia.register();

val molten_skythern = mods.contenttweaker.VanillaFactory.createFluid("skythern", Color.fromHex("777777").getIntColor()); 
molten_skythern.material = <blockmaterial:lava>;
molten_skythern.viscosity = 3000;
molten_skythern.density = 6500;
molten_skythern.colorize = true;
molten_skythern.temperature = 1000;
molten_skythern.luminosity = 10;
molten_skythern.color = Color.fromHex("777777").getIntColor();
molten_skythern.stillLocation = "base:fluids/molten";
molten_skythern.flowingLocation = "base:fluids/molten_flowing";
molten_skythern.register();

val molten_mortum = mods.contenttweaker.VanillaFactory.createFluid("mortum", Color.fromHex("3f3f3f").getIntColor()); 
molten_mortum.material = <blockmaterial:lava>;
molten_mortum.viscosity = 3000;
molten_mortum.density = 6500;
molten_mortum.colorize = true;
molten_mortum.temperature = 1000;
molten_mortum.luminosity = 10;
molten_mortum.color = Color.fromHex("3f3f3f").getIntColor();
molten_mortum.stillLocation = "base:fluids/molten";
molten_mortum.flowingLocation = "base:fluids/molten_flowing";
molten_mortum.register();

val molten_twilight_crystal = mods.contenttweaker.VanillaFactory.createFluid("twilight_crystal", Color.fromHex("189800").getIntColor()); 
molten_twilight_crystal.material = <blockmaterial:lava>;
molten_twilight_crystal.viscosity = 3000;
molten_twilight_crystal.density = 6500;
molten_twilight_crystal.colorize = true;
molten_twilight_crystal.temperature = 1000;
molten_twilight_crystal.luminosity = 10;
molten_twilight_crystal.color = Color.fromHex("189800").getIntColor();
molten_twilight_crystal.stillLocation = "base:fluids/molten";
molten_twilight_crystal.flowingLocation = "base:fluids/molten_flowing";
molten_twilight_crystal.register();

//gt 2

val molten_hellcrust = mods.contenttweaker.VanillaFactory.createFluid("hellcrust", Color.fromHex("505050").getIntColor()); 
molten_hellcrust.material = <blockmaterial:lava>;
molten_hellcrust.viscosity = 3000;
molten_hellcrust.density = 6500;
molten_hellcrust.colorize = true;
molten_hellcrust.temperature = 1000;
molten_hellcrust.luminosity = 10;
molten_hellcrust.color = Color.fromHex("505050").getIntColor();
molten_hellcrust.stillLocation = "base:fluids/molten";
molten_hellcrust.flowingLocation = "base:fluids/molten_flowing";
molten_hellcrust.register();

val molten_umbra = mods.contenttweaker.VanillaFactory.createFluid("umbra", Color.fromHex("3f4c52").getIntColor()); 
molten_umbra.material = <blockmaterial:lava>;
molten_umbra.viscosity = 3000;
molten_umbra.density = 6500;
molten_umbra.colorize = true;
molten_umbra.temperature = 1000;
molten_umbra.luminosity = 10;
molten_umbra.color = Color.fromHex("3f4c52").getIntColor();
molten_umbra.stillLocation = "base:fluids/molten";
molten_umbra.flowingLocation = "base:fluids/molten_flowing";
molten_umbra.register();

val molten_crystalline = mods.contenttweaker.VanillaFactory.createFluid("crystalline", Color.fromHex("fef2ff").getIntColor()); 
molten_crystalline.material = <blockmaterial:lava>;
molten_crystalline.viscosity = 3000;
molten_crystalline.density = 6500;
molten_crystalline.colorize = true;
molten_crystalline.temperature = 1000;
molten_crystalline.luminosity = 10;
molten_crystalline.color = Color.fromHex("fef2ff").getIntColor();
molten_crystalline.stillLocation = "base:fluids/molten";
molten_crystalline.flowingLocation = "base:fluids/molten_flowing";
molten_crystalline.register();

val molten_aurorianite = mods.contenttweaker.VanillaFactory.createFluid("aurorianite", Color.fromHex("adbcff").getIntColor()); 
molten_aurorianite.material = <blockmaterial:lava>;
molten_aurorianite.viscosity = 3000;
molten_aurorianite.density = 6500;
molten_aurorianite.colorize = true;
molten_aurorianite.temperature = 1000;
molten_aurorianite.luminosity = 10;
molten_aurorianite.color = Color.fromHex("adbcff").getIntColor();
molten_aurorianite.stillLocation = "base:fluids/molten";
molten_aurorianite.flowingLocation = "base:fluids/molten_flowing";
molten_aurorianite.register();

val molten_niobium = mods.contenttweaker.VanillaFactory.createFluid("niobium", Color.fromHex("d1d3df").getIntColor()); 
molten_niobium.material = <blockmaterial:lava>;
molten_niobium.viscosity = 3000;
molten_niobium.density = 6500;
molten_niobium.colorize = true;
molten_niobium.temperature = 1000;
molten_niobium.luminosity = 10;
molten_niobium.color = Color.fromHex("d1d3df").getIntColor();
molten_niobium.stillLocation = "base:fluids/molten";
molten_niobium.flowingLocation = "base:fluids/molten_flowing";
molten_niobium.register();

val molten_horizonite = mods.contenttweaker.VanillaFactory.createFluid("horizonite", Color.fromHex("fcab39").getIntColor()); 
molten_horizonite.material = <blockmaterial:lava>;
molten_horizonite.viscosity = 3000;
molten_horizonite.density = 6500;
molten_horizonite.colorize = true;
molten_horizonite.temperature = 1000;
molten_horizonite.luminosity = 10;
molten_horizonite.color = Color.fromHex("fcab39").getIntColor();
molten_horizonite.stillLocation = "base:fluids/molten";
molten_horizonite.flowingLocation = "base:fluids/molten_flowing";
molten_horizonite.register();

val molten_falsite = mods.contenttweaker.VanillaFactory.createFluid("falsite", Color.fromHex("7561e2").getIntColor()); 
molten_falsite.material = <blockmaterial:lava>;
molten_falsite.viscosity = 3000;
molten_falsite.density = 6500;
molten_falsite.colorize = true;
molten_falsite.temperature = 1000;
molten_falsite.luminosity = 10;
molten_falsite.color = Color.fromHex("7561e2").getIntColor();
molten_falsite.stillLocation = "base:fluids/molten";
molten_falsite.flowingLocation = "base:fluids/molten_flowing";
molten_falsite.register();

val molten_ventium = mods.contenttweaker.VanillaFactory.createFluid("ventium", Color.fromHex("cf2532").getIntColor()); 
molten_ventium.material = <blockmaterial:lava>;
molten_ventium.viscosity = 3000;
molten_ventium.density = 6500;
molten_ventium.colorize = true;
molten_ventium.temperature = 1000;
molten_ventium.luminosity = 10;
molten_ventium.color = Color.fromHex("cf2532").getIntColor();
molten_ventium.stillLocation = "base:fluids/molten";
molten_ventium.flowingLocation = "base:fluids/molten_flowing";
molten_ventium.register();

val molten_apocalypsium = mods.contenttweaker.VanillaFactory.createFluid("apocalypsium", Color.fromHex("8b0000").getIntColor()); 
molten_apocalypsium.material = <blockmaterial:lava>;
molten_apocalypsium.viscosity = 3000;
molten_apocalypsium.density = 6500;
molten_apocalypsium.colorize = true;
molten_apocalypsium.temperature = 1000;
molten_apocalypsium.luminosity = 10;
molten_apocalypsium.color = Color.fromHex("8b0000").getIntColor();
molten_apocalypsium.stillLocation = "base:fluids/molten";
molten_apocalypsium.flowingLocation = "base:fluids/molten_flowing";
molten_apocalypsium.register();

val molten_sanite = mods.contenttweaker.VanillaFactory.createFluid("sanite", Color.fromHex("eeeeee").getIntColor());
molten_sanite.material = <blockmaterial:lava>;
molten_sanite.viscosity = 3000;
molten_sanite.density = 6500;
molten_sanite.colorize = true;
molten_sanite.temperature = 1000;
molten_sanite.luminosity = 10;
molten_sanite.color = Color.fromHex("eeeeee").getIntColor();
molten_sanite.stillLocation = "base:fluids/molten";
molten_sanite.flowingLocation = "base:fluids/molten_flowing";
molten_sanite.register();

val molten_harcadium = mods.contenttweaker.VanillaFactory.createFluid("harcadium", Color.fromHex("ce8cff").getIntColor());
molten_harcadium.material = <blockmaterial:lava>;
molten_harcadium.viscosity = 3000;
molten_harcadium.density = 6500;
molten_harcadium.colorize = true;
molten_harcadium.temperature = 1000;
molten_harcadium.luminosity = 10;
molten_harcadium.color = Color.fromHex("ce8cff").getIntColor();
molten_harcadium.stillLocation = "base:fluids/molten";
molten_harcadium.flowingLocation = "base:fluids/molten_flowing";
molten_harcadium.register();

val molten_void_essence = mods.contenttweaker.VanillaFactory.createFluid("void_essence", Color.fromHex("000000").getIntColor());
molten_void_essence.material = <blockmaterial:lava>;
molten_void_essence.viscosity = 3000;
molten_void_essence.density = 6500;
molten_void_essence.colorize = true;
molten_void_essence.temperature = 1000;
molten_void_essence.luminosity = 10;
molten_void_essence.color = Color.fromHex("000000").getIntColor();
molten_void_essence.stillLocation = "base:fluids/molten";
molten_void_essence.flowingLocation = "base:fluids/molten_flowing";
molten_void_essence.register();

val molten_adamantium = mods.contenttweaker.VanillaFactory.createFluid("adamantium", Color.fromHex("bcbbbb").getIntColor());
molten_adamantium.material = <blockmaterial:lava>;
molten_adamantium.viscosity = 3000;
molten_adamantium.density = 6500;
molten_adamantium.colorize = true;
molten_adamantium.temperature = 1000;
molten_adamantium.luminosity = 10;
molten_adamantium.color = Color.fromHex("bcbbbb").getIntColor();
molten_adamantium.stillLocation = "base:fluids/molten";
molten_adamantium.flowingLocation = "base:fluids/molten_flowing";
molten_adamantium.register();

val molten_hellite = mods.contenttweaker.VanillaFactory.createFluid("hellite", Color.fromHex("673535").getIntColor());
molten_hellite.material = <blockmaterial:lava>;
molten_hellite.viscosity = 3000;
molten_hellite.density = 6500;
molten_hellite.colorize = true;
molten_hellite.temperature = 1000;
molten_hellite.luminosity = 10;
molten_hellite.color = Color.fromHex("673535").getIntColor();
molten_hellite.stillLocation = "base:fluids/molten";
molten_hellite.flowingLocation = "base:fluids/molten_flowing";
molten_hellite.register();

val molten_blackhole_alloy = mods.contenttweaker.VanillaFactory.createFluid("blackhole_alloy", Color.fromHex("000000").getIntColor());
molten_blackhole_alloy.material = <blockmaterial:lava>;
molten_blackhole_alloy.viscosity = 3000;
molten_blackhole_alloy.density = 6500;
molten_blackhole_alloy.colorize = true;
molten_blackhole_alloy.temperature = 1000;
molten_blackhole_alloy.luminosity = 10;
molten_blackhole_alloy.color = Color.fromHex("000000").getIntColor();
molten_blackhole_alloy.stillLocation = "base:fluids/molten";
molten_blackhole_alloy.flowingLocation = "base:fluids/molten_flowing";
molten_blackhole_alloy.register();

val molten_creative_alloy = mods.contenttweaker.VanillaFactory.createFluid("creative_alloy", Color.fromHex("f25b6e").getIntColor());
molten_creative_alloy.material = <blockmaterial:lava>;
molten_creative_alloy.viscosity = 3000;
molten_creative_alloy.density = 6500;
molten_creative_alloy.colorize = true;
molten_creative_alloy.temperature = 1000;
molten_creative_alloy.luminosity = 10;
molten_creative_alloy.color = Color.fromHex("f25b6e").getIntColor();
molten_creative_alloy.stillLocation = "base:fluids/molten";
molten_creative_alloy.flowingLocation = "base:fluids/molten_flowing";
molten_creative_alloy.register();

val molten_ruthenium = mods.contenttweaker.VanillaFactory.createFluid("ruthenium", Color.fromHex("4a4a4a").getIntColor());
molten_ruthenium.material = <blockmaterial:lava>;
molten_ruthenium.viscosity = 3000;
molten_ruthenium.density = 6500;
molten_ruthenium.colorize = true;
molten_ruthenium.temperature = 1000;
molten_ruthenium.luminosity = 10;
molten_ruthenium.color = Color.fromHex("4a4a4a").getIntColor();
molten_ruthenium.stillLocation = "base:fluids/molten";
molten_ruthenium.flowingLocation = "base:fluids/molten_flowing";
molten_ruthenium.register();

val molten_rhodium = mods.contenttweaker.VanillaFactory.createFluid("rhodium", Color.fromHex("a07074").getIntColor());
molten_rhodium.material = <blockmaterial:lava>;
molten_rhodium.viscosity = 3000;
molten_rhodium.density = 6500;
molten_rhodium.colorize = true;
molten_rhodium.temperature = 1000;
molten_rhodium.luminosity = 10;
molten_rhodium.color = Color.fromHex("a07074").getIntColor();
molten_rhodium.stillLocation = "base:fluids/molten";
molten_rhodium.flowingLocation = "base:fluids/molten_flowing";
molten_rhodium.register();

val molten_porpezite = mods.contenttweaker.VanillaFactory.createFluid("porpezite", Color.fromHex("bebea2").getIntColor());
molten_porpezite.material = <blockmaterial:lava>;
molten_porpezite.viscosity = 3000;
molten_porpezite.density = 6500;
molten_porpezite.colorize = true;
molten_porpezite.temperature = 1000;
molten_porpezite.luminosity = 10;
molten_porpezite.color = Color.fromHex("bebea2").getIntColor();
molten_porpezite.stillLocation = "base:fluids/molten";
molten_porpezite.flowingLocation = "base:fluids/molten_flowing";
molten_porpezite.register();

val molten_raisium = mods.contenttweaker.VanillaFactory.createFluid("raisium", Color.fromHex("a8acac").getIntColor());
molten_raisium.material = <blockmaterial:lava>;
molten_raisium.viscosity = 3000;
molten_raisium.density = 6500;
molten_raisium.colorize = true;
molten_raisium.temperature = 1000;
molten_raisium.luminosity = 10;
molten_raisium.color = Color.fromHex("a8acac").getIntColor();
molten_raisium.stillLocation = "base:fluids/molten";
molten_raisium.flowingLocation = "base:fluids/molten_flowing";
molten_raisium.register();

val molten_astronicium = mods.contenttweaker.VanillaFactory.createFluid("astronicium", Color.fromHex("562f88").getIntColor());
molten_astronicium.material = <blockmaterial:lava>;
molten_astronicium.viscosity = 3000;
molten_astronicium.density = 6500;
molten_astronicium.colorize = true;
molten_astronicium.temperature = 1000;
molten_astronicium.luminosity = 10;
molten_astronicium.color = Color.fromHex("562f88").getIntColor();
molten_astronicium.stillLocation = "base:fluids/molten";
molten_astronicium.flowingLocation = "base:fluids/molten_flowing";
molten_astronicium.register();

val molten_compressite = mods.contenttweaker.VanillaFactory.createFluid("compressite", Color.fromHex("403652").getIntColor());
molten_compressite.material = <blockmaterial:lava>;
molten_compressite.viscosity = 3000;
molten_compressite.density = 6500;
molten_compressite.colorize = true;
molten_compressite.temperature = 1000;
molten_compressite.luminosity = 10;
molten_compressite.color = Color.fromHex("403652").getIntColor();
molten_compressite.stillLocation = "base:fluids/molten";
molten_compressite.flowingLocation = "base:fluids/molten_flowing";
molten_compressite.register();

val molten_dullium = mods.contenttweaker.VanillaFactory.createFluid("dullium", Color.fromHex("000000").getIntColor());
molten_dullium.material = <blockmaterial:lava>;
molten_dullium.viscosity = 3000;
molten_dullium.density = 6500;
molten_dullium.colorize = true;
molten_dullium.temperature = 1000;
molten_dullium.luminosity = 10;
molten_dullium.color = Color.fromHex("000000").getIntColor();
molten_dullium.stillLocation = "base:fluids/molten";
molten_dullium.flowingLocation = "base:fluids/molten_flowing";
molten_dullium.register();

val molten_daynight = mods.contenttweaker.VanillaFactory.createFluid("daynight", Color.fromHex("203c96").getIntColor());
molten_daynight.material = <blockmaterial:lava>;
molten_daynight.viscosity = 3000;
molten_daynight.density = 6500;
molten_daynight.colorize = true;
molten_daynight.temperature = 1000;
molten_daynight.luminosity = 10;
molten_daynight.color = Color.fromHex("203c96").getIntColor();
molten_daynight.stillLocation = "base:fluids/molten";
molten_daynight.flowingLocation = "base:fluids/molten_flowing";
molten_daynight.register();

val molten_mythsteel = mods.contenttweaker.VanillaFactory.createFluid("mythsteel", Color.fromHex("e8ae31").getIntColor());
molten_mythsteel.material = <blockmaterial:lava>;
molten_mythsteel.viscosity = 3000;
molten_mythsteel.density = 6500;
molten_mythsteel.colorize = true;
molten_mythsteel.temperature = 1000;
molten_mythsteel.luminosity = 10;
molten_mythsteel.color = Color.fromHex("e8ae31").getIntColor();
molten_mythsteel.stillLocation = "base:fluids/molten";
molten_mythsteel.flowingLocation = "base:fluids/molten_flowing";
molten_mythsteel.register();

val molten_cthulhurite = mods.contenttweaker.VanillaFactory.createFluid("cthulhurite", Color.fromHex("15595d").getIntColor());
molten_cthulhurite.material = <blockmaterial:lava>;
molten_cthulhurite.viscosity = 3000;
molten_cthulhurite.density = 6500;
molten_cthulhurite.colorize = true;
molten_cthulhurite.temperature = 1000;
molten_cthulhurite.luminosity = 10;
molten_cthulhurite.color = Color.fromHex("15595d").getIntColor();
molten_cthulhurite.stillLocation = "base:fluids/molten";
molten_cthulhurite.flowingLocation = "base:fluids/molten_flowing";
molten_cthulhurite.register();

val molten_elfsteel = mods.contenttweaker.VanillaFactory.createFluid("elfsteel", Color.fromHex("d08700").getIntColor());
molten_elfsteel.material = <blockmaterial:lava>;
molten_elfsteel.viscosity = 3000;
molten_elfsteel.density = 6500;
molten_elfsteel.colorize = true;
molten_elfsteel.temperature = 1000;
molten_elfsteel.luminosity = 10;
molten_elfsteel.color = Color.fromHex("d08700").getIntColor();
molten_elfsteel.stillLocation = "base:fluids/molten";
molten_elfsteel.flowingLocation = "base:fluids/molten_flowing";
molten_elfsteel.register();

val molten_chillinium = mods.contenttweaker.VanillaFactory.createFluid("chillinium", Color.fromHex("6ddae6").getIntColor());
molten_chillinium.material = <blockmaterial:lava>;
molten_chillinium.viscosity = 3000;
molten_chillinium.density = 6500;
molten_chillinium.colorize = true;
molten_chillinium.temperature = 1000;
molten_chillinium.luminosity = 10;
molten_chillinium.color = Color.fromHex("6ddae6").getIntColor();
molten_chillinium.stillLocation = "base:fluids/molten";
molten_chillinium.flowingLocation = "base:fluids/molten_flowing";
molten_chillinium.register();

val molten_iciricium = mods.contenttweaker.VanillaFactory.createFluid("iciricium", Color.fromHex("216643").getIntColor());
molten_iciricium.material = <blockmaterial:lava>;
molten_iciricium.viscosity = 3000;
molten_iciricium.density = 6500;
molten_iciricium.colorize = true;
molten_iciricium.temperature = 1000;
molten_iciricium.luminosity = 10;
molten_iciricium.color = Color.fromHex("216643").getIntColor();
molten_iciricium.stillLocation = "base:fluids/molten";
molten_iciricium.flowingLocation = "base:fluids/molten_flowing";
molten_iciricium.register();

val molten_moltenium = mods.contenttweaker.VanillaFactory.createFluid("moltenium", Color.fromHex("e03b1a").getIntColor());
molten_moltenium.material = <blockmaterial:lava>;
molten_moltenium.viscosity = 3000;
molten_moltenium.density = 6500;
molten_moltenium.colorize = true;
molten_moltenium.temperature = 10000;
molten_moltenium.luminosity = 10;
molten_moltenium.color = Color.fromHex("e03b1a").getIntColor();
molten_moltenium.stillLocation = "base:fluids/molten";
molten_moltenium.flowingLocation = "base:fluids/molten_flowing";
molten_moltenium.register();

val molten_typhoonite = mods.contenttweaker.VanillaFactory.createFluid("typhoonite", Color.fromHex("d5fcaf").getIntColor());
molten_typhoonite.material = <blockmaterial:lava>;
molten_typhoonite.viscosity = 3000;
molten_typhoonite.density = 6500;
molten_typhoonite.colorize = true;
molten_typhoonite.temperature = 1000;
molten_typhoonite.luminosity = 10;
molten_typhoonite.color = Color.fromHex("d5fcaf").getIntColor();
molten_typhoonite.stillLocation = "base:fluids/molten";
molten_typhoonite.flowingLocation = "base:fluids/molten_flowing";
molten_typhoonite.register();

val molten_liquidlegend = mods.contenttweaker.VanillaFactory.createFluid("liquidlegend", Color.fromHex("ffcf4b").getIntColor());
molten_liquidlegend.material = <blockmaterial:lava>;
molten_liquidlegend.viscosity = 3000;
molten_liquidlegend.density = 6500;
molten_liquidlegend.colorize = true;
molten_liquidlegend.temperature = 1000;
molten_liquidlegend.luminosity = 10;
molten_liquidlegend.color = Color.fromHex("ffcf4b").getIntColor();
molten_liquidlegend.stillLocation = "base:fluids/molten";
molten_liquidlegend.flowingLocation = "base:fluids/molten_flowing";
molten_liquidlegend.register();

val molten_thermallite = mods.contenttweaker.VanillaFactory.createFluid("thermallite", Color.fromHex("4fffff").getIntColor());
molten_thermallite.material = <blockmaterial:lava>;
molten_thermallite.viscosity = 3000;
molten_thermallite.density = 6500;
molten_thermallite.colorize = true;
molten_thermallite.temperature = 36000;
molten_thermallite.luminosity = 10;
molten_thermallite.color = Color.fromHex("4fffff").getIntColor();
molten_thermallite.stillLocation = "base:fluids/molten";
molten_thermallite.flowingLocation = "base:fluids/molten_flowing";
molten_thermallite.register();

val molten_photonium = mods.contenttweaker.VanillaFactory.createFluid("photonium", Color.fromHex("e0e0e0").getIntColor());
molten_photonium.material = <blockmaterial:lava>;
molten_photonium.viscosity = 3000;
molten_photonium.density = 6500;
molten_photonium.colorize = true;
molten_photonium.temperature = 8000;
molten_photonium.luminosity = 10;
molten_photonium.color = Color.fromHex("e0e0e0").getIntColor();
molten_photonium.stillLocation = "base:fluids/molten";
molten_photonium.flowingLocation = "base:fluids/molten_flowing";
molten_photonium.register();

val molten_mercury = mods.contenttweaker.VanillaFactory.createFluid("mercury", Color.fromHex("d1c8c1").getIntColor());
molten_mercury.material = <blockmaterial:water>;
molten_mercury.viscosity = 3000;
molten_mercury.density = 12900;
molten_mercury.colorize = true;
molten_mercury.temperature = 300;
molten_mercury.luminosity = 0;
molten_mercury.color = Color.fromHex("d1c8c1").getIntColor();
molten_mercury.stillLocation = "base:fluids/liquid";
molten_mercury.flowingLocation = "base:fluids/liquid_flow";
molten_mercury.register();

val molten_enderiron = mods.contenttweaker.VanillaFactory.createFluid("enderiron", Color.fromHex("006201").getIntColor());
molten_enderiron.material = <blockmaterial:lava>;
molten_enderiron.viscosity = 3000;
molten_enderiron.density = 6500;
molten_enderiron.colorize = true;
molten_enderiron.temperature = 1000;
molten_enderiron.luminosity = 10;
molten_enderiron.color = Color.fromHex("006201").getIntColor();
molten_enderiron.stillLocation = "base:fluids/molten";
molten_enderiron.flowingLocation = "base:fluids/molten_flowing";
molten_enderiron.register();

val molten_enderironex = mods.contenttweaker.VanillaFactory.createFluid("enderironex", Color.fromHex("022503").getIntColor());
molten_enderironex.material = <blockmaterial:lava>;
molten_enderironex.viscosity = 3000;
molten_enderironex.density = 6500;
molten_enderironex.colorize = true;
molten_enderironex.temperature = 1000;
molten_enderironex.luminosity = 10;
molten_enderironex.color = Color.fromHex("022503").getIntColor();
molten_enderironex.stillLocation = "base:fluids/molten";
molten_enderironex.flowingLocation = "base:fluids/molten_flowing";
molten_enderironex.register();

val molten_crystaltine = mods.contenttweaker.VanillaFactory.createFluid("crystaltine", Color.fromHex("b7cbbf").getIntColor());
molten_crystaltine.material = <blockmaterial:lava>;
molten_crystaltine.viscosity = 3000;
molten_crystaltine.density = 6500;
molten_crystaltine.colorize = true;
molten_crystaltine.temperature = 1000;
molten_crystaltine.luminosity = 10;
molten_crystaltine.color = Color.fromHex("b7cbbf").getIntColor();
molten_crystaltine.stillLocation = "base:fluids/molten";
molten_crystaltine.flowingLocation = "base:fluids/molten_flowing";
molten_crystaltine.register();

val molten_caesium = mods.contenttweaker.VanillaFactory.createFluid("caesium", Color.fromHex("ffff8b").getIntColor());
molten_caesium.material = <blockmaterial:lava>;
molten_caesium.viscosity = 3000;
molten_caesium.density = 6500;
molten_caesium.colorize = true;
molten_caesium.temperature = 1000;
molten_caesium.luminosity = 10;
molten_caesium.color = Color.fromHex("ffff8b").getIntColor();
molten_caesium.stillLocation = "base:fluids/molten";
molten_caesium.flowingLocation = "base:fluids/molten_flowing";
molten_caesium.register();

val molten_rubidium = mods.contenttweaker.VanillaFactory.createFluid("rubidium", Color.fromHex("9b0000").getIntColor());
molten_rubidium.material = <blockmaterial:lava>;
molten_rubidium.viscosity = 3000;
molten_rubidium.density = 6500;
molten_rubidium.colorize = true;
molten_rubidium.temperature = 1000;
molten_rubidium.luminosity = 10;
molten_rubidium.color = Color.fromHex("9b0000").getIntColor();
molten_rubidium.stillLocation = "base:fluids/molten";
molten_rubidium.flowingLocation = "base:fluids/molten_flowing";
molten_rubidium.register();

val molten_francium = mods.contenttweaker.VanillaFactory.createFluid("francium", Color.fromHex("00eb00").getIntColor());
molten_francium.material = <blockmaterial:lava>;
molten_francium.viscosity = 3000;
molten_francium.density = 6500;
molten_francium.colorize = true;
molten_francium.temperature = 1000;
molten_francium.luminosity = 10;
molten_francium.color = Color.fromHex("00eb00").getIntColor();
molten_francium.stillLocation = "base:fluids/molten";
molten_francium.flowingLocation = "base:fluids/molten_flowing";
molten_francium.register();

val molten_zodiacite = mods.contenttweaker.VanillaFactory.createFluid("zodiacite", Color.fromHex("3cffff").getIntColor());
molten_zodiacite.material = <blockmaterial:lava>;
molten_zodiacite.viscosity = 3000;
molten_zodiacite.density = 6500;
molten_zodiacite.colorize = true;
molten_zodiacite.temperature = 1000;
molten_zodiacite.luminosity = 10;
molten_zodiacite.color = Color.fromHex("3cffff").getIntColor();
molten_zodiacite.stillLocation = "base:fluids/molten";
molten_zodiacite.flowingLocation = "base:fluids/molten_flowing";
molten_zodiacite.register();

val molten_azathothium = mods.contenttweaker.VanillaFactory.createFluid("azathothium", Color.fromHex("506d61").getIntColor());
molten_azathothium.material = <blockmaterial:lava>;
molten_azathothium.viscosity = 3000;
molten_azathothium.density = 6500;
molten_azathothium.colorize = true;
molten_azathothium.temperature = 1000;
molten_azathothium.luminosity = 10;
molten_azathothium.color = Color.fromHex("506d61").getIntColor();
molten_azathothium.stillLocation = "base:fluids/molten";
molten_azathothium.flowingLocation = "base:fluids/molten_flowing";
molten_azathothium.register();

val molten_nyarlathotepium = mods.contenttweaker.VanillaFactory.createFluid("nyarlathotepium", Color.fromHex("5a4b44").getIntColor());
molten_nyarlathotepium.material = <blockmaterial:lava>;
molten_nyarlathotepium.viscosity = 3000;
molten_nyarlathotepium.density = 6500;
molten_nyarlathotepium.colorize = true;
molten_nyarlathotepium.temperature = 1000;
molten_nyarlathotepium.luminosity = 10;
molten_nyarlathotepium.color = Color.fromHex("5a4b44").getIntColor();
molten_nyarlathotepium.stillLocation = "base:fluids/molten";
molten_nyarlathotepium.flowingLocation = "base:fluids/molten_flowing";
molten_nyarlathotepium.register();

val molten_yogsothothium = mods.contenttweaker.VanillaFactory.createFluid("yogsothothium", Color.fromHex("8c74a8").getIntColor());
molten_yogsothothium.material = <blockmaterial:lava>;
molten_yogsothothium.viscosity = 3000;
molten_yogsothothium.density = 6500;
molten_yogsothothium.colorize = true;
molten_yogsothothium.temperature = 1000;
molten_yogsothothium.luminosity = 10;
molten_yogsothothium.color = Color.fromHex("8c74a8").getIntColor();
molten_yogsothothium.stillLocation = "base:fluids/molten";
molten_yogsothothium.flowingLocation = "base:fluids/molten_flowing";
molten_yogsothothium.register();

val molten_shubniggurathium = mods.contenttweaker.VanillaFactory.createFluid("shubniggurathium", Color.fromHex("798188").getIntColor());
molten_shubniggurathium.material = <blockmaterial:lava>;
molten_shubniggurathium.viscosity = 3000;
molten_shubniggurathium.density = 6500;
molten_shubniggurathium.colorize = true;
molten_shubniggurathium.temperature = 1000;
molten_shubniggurathium.luminosity = 10;
molten_shubniggurathium.color = Color.fromHex("798188").getIntColor();
molten_shubniggurathium.stillLocation = "base:fluids/molten";
molten_shubniggurathium.flowingLocation = "base:fluids/molten_flowing";
molten_shubniggurathium.register();

val molten_nasalum = mods.contenttweaker.VanillaFactory.createFluid("nasalum", Color.fromHex("0d559e").getIntColor());
molten_nasalum.material = <blockmaterial:lava>;
molten_nasalum.viscosity = 3000;
molten_nasalum.density = 6500;
molten_nasalum.colorize = true;
molten_nasalum.temperature = 1000;
molten_nasalum.luminosity = 10;
molten_nasalum.color = Color.fromHex("0d559e").getIntColor();
molten_nasalum.stillLocation = "base:fluids/molten";
molten_nasalum.flowingLocation = "base:fluids/molten_flowing";
molten_nasalum.register();

val molten_lunarine = mods.contenttweaker.VanillaFactory.createFluid("lunarine", Color.fromHex("f1f1f1").getIntColor());
molten_lunarine.material = <blockmaterial:lava>;
molten_lunarine.viscosity = 3000;
molten_lunarine.density = 6500;
molten_lunarine.colorize = true;
molten_lunarine.temperature = 1000;
molten_lunarine.luminosity = 10;
molten_lunarine.color = Color.fromHex("f1f1f1").getIntColor();
molten_lunarine.stillLocation = "base:fluids/molten";
molten_lunarine.flowingLocation = "base:fluids/molten_flowing";
molten_lunarine.register();

val molten_darkest = mods.contenttweaker.VanillaFactory.createFluid("darkest", Color.fromHex("000000").getIntColor());
molten_darkest.material = <blockmaterial:lava>;
molten_darkest.viscosity = 3000;
molten_darkest.density = 6500;
molten_darkest.colorize = true;
molten_darkest.temperature = 1000;
molten_darkest.luminosity = 10;
molten_darkest.color = Color.fromHex("000000").getIntColor();
molten_darkest.stillLocation = "base:fluids/molten";
molten_darkest.flowingLocation = "base:fluids/molten_flowing";
molten_darkest.register();

val molten_wigthium = mods.contenttweaker.VanillaFactory.createFluid("wigthium", Color.fromHex("bababa").getIntColor());
molten_wigthium.material = <blockmaterial:lava>;
molten_wigthium.viscosity = 3000;
molten_wigthium.density = 6500;
molten_wigthium.colorize = true;
molten_wigthium.temperature = 1000;
molten_wigthium.luminosity = 10;
molten_wigthium.color = Color.fromHex("bababa").getIntColor();
molten_wigthium.stillLocation = "base:fluids/molten";
molten_wigthium.flowingLocation = "base:fluids/molten_flowing";
molten_wigthium.register();

val molten_murderite = mods.contenttweaker.VanillaFactory.createFluid("murderite", Color.fromHex("a73570").getIntColor());
molten_murderite.material = <blockmaterial:lava>;
molten_murderite.viscosity = 3000;
molten_murderite.density = 6500;
molten_murderite.colorize = true;
molten_murderite.temperature = 1000;
molten_murderite.luminosity = 10;
molten_murderite.color = Color.fromHex("a73570").getIntColor();
molten_murderite.stillLocation = "base:fluids/molten";
molten_murderite.flowingLocation = "base:fluids/molten_flowing";
molten_murderite.register();

val molten_ghost_metal = mods.contenttweaker.VanillaFactory.createFluid("ghost_metal", Color.fromHex("013148").getIntColor());
molten_ghost_metal.material = <blockmaterial:lava>;
molten_ghost_metal.viscosity = 3000;
molten_ghost_metal.density = 6500;
molten_ghost_metal.colorize = true;
molten_ghost_metal.temperature = 1000;
molten_ghost_metal.luminosity = 10;
molten_ghost_metal.color = Color.fromHex("013148").getIntColor();
molten_ghost_metal.stillLocation = "base:fluids/molten";
molten_ghost_metal.flowingLocation = "base:fluids/molten_flowing";
molten_ghost_metal.register();

val molten_impetusite = mods.contenttweaker.VanillaFactory.createFluid("impetusite", Color.fromHex("eeeeee").getIntColor());
molten_impetusite.material = <blockmaterial:lava>;
molten_impetusite.viscosity = 3000;
molten_impetusite.density = 6500;
molten_impetusite.colorize = true;
molten_impetusite.temperature = 1000;
molten_impetusite.luminosity = 10;
molten_impetusite.color = Color.fromHex("eeeeee").getIntColor();
molten_impetusite.stillLocation = "base:fluids/molten";
molten_impetusite.flowingLocation = "base:fluids/molten_flowing";
molten_impetusite.register();

val molten_eldritch_steel = mods.contenttweaker.VanillaFactory.createFluid("eldritch_steel", Color.fromHex("5e0057").getIntColor());
molten_eldritch_steel.material = <blockmaterial:lava>;
molten_eldritch_steel.viscosity = 3000;
molten_eldritch_steel.density = 6500;
molten_eldritch_steel.colorize = true;
molten_eldritch_steel.temperature = 1000;
molten_eldritch_steel.luminosity = 10;
molten_eldritch_steel.color = Color.fromHex("5e0057").getIntColor();
molten_eldritch_steel.stillLocation = "base:fluids/molten";
molten_eldritch_steel.flowingLocation = "base:fluids/molten_flowing";
molten_eldritch_steel.register();

val molten_corruptium = mods.contenttweaker.VanillaFactory.createFluid("corruptium", Color.fromHex("2c0a59").getIntColor());
molten_corruptium.material = <blockmaterial:lava>;
molten_corruptium.viscosity = 3000;
molten_corruptium.density = 6500;
molten_corruptium.colorize = true;
molten_corruptium.temperature = 1000;
molten_corruptium.luminosity = 10;
molten_corruptium.color = Color.fromHex("2c0a59").getIntColor();
molten_corruptium.stillLocation = "base:fluids/molten";
molten_corruptium.flowingLocation = "base:fluids/molten_flowing";
molten_corruptium.register();

val molten_cursium = mods.contenttweaker.VanillaFactory.createFluid("cursium", Color.fromHex("8e1c7b").getIntColor());
molten_cursium.material = <blockmaterial:lava>;
molten_cursium.viscosity = 3000;
molten_cursium.density = 6500;
molten_cursium.colorize = true;
molten_cursium.temperature = 1000;
molten_cursium.luminosity = 10;
molten_cursium.color = Color.fromHex("8e1c7b").getIntColor();
molten_cursium.stillLocation = "base:fluids/molten";
molten_cursium.flowingLocation = "base:fluids/molten_flowing";
molten_cursium.register();

val molten_botanical = mods.contenttweaker.VanillaFactory.createFluid("botanical", Color.fromHex("abf1ab").getIntColor());
molten_botanical.material = <blockmaterial:lava>;
molten_botanical.viscosity = 3000;
molten_botanical.density = 6500;
molten_botanical.colorize = true;
molten_botanical.temperature = 1000;
molten_botanical.luminosity = 10;
molten_botanical.color = Color.fromHex("abf1ab").getIntColor();
molten_botanical.stillLocation = "base:fluids/molten";
molten_botanical.flowingLocation = "base:fluids/molten_flowing";
molten_botanical.register();

val molten_rosium = mods.contenttweaker.VanillaFactory.createFluid("rosium", Color.fromHex("ff2c45").getIntColor());
molten_rosium.material = <blockmaterial:lava>;
molten_rosium.viscosity = 3000;
molten_rosium.density = 6500;
molten_rosium.colorize = true;
molten_rosium.temperature = 1000;
molten_rosium.luminosity = 10;
molten_rosium.color = Color.fromHex("ff2c45").getIntColor();
molten_rosium.stillLocation = "base:fluids/molten";
molten_rosium.flowingLocation = "base:fluids/molten_flowing";
molten_rosium.register();

val molten_chrysanthemium = mods.contenttweaker.VanillaFactory.createFluid("chrysanthemium", Color.fromHex("ff9f01").getIntColor());
molten_chrysanthemium.material = <blockmaterial:lava>;
molten_chrysanthemium.viscosity = 3000;
molten_chrysanthemium.density = 6500;
molten_chrysanthemium.colorize = true;
molten_chrysanthemium.temperature = 1000;
molten_chrysanthemium.luminosity = 10;
molten_chrysanthemium.color = Color.fromHex("ff9f01").getIntColor();
molten_chrysanthemium.stillLocation = "base:fluids/molten";
molten_chrysanthemium.flowingLocation = "base:fluids/molten_flowing";
molten_chrysanthemium.register();

val molten_dandelionium = mods.contenttweaker.VanillaFactory.createFluid("dandelionium", Color.fromHex("ffffff").getIntColor());
molten_dandelionium.material = <blockmaterial:lava>;
molten_dandelionium.viscosity = 3000;
molten_dandelionium.density = 6500;
molten_dandelionium.colorize = true;
molten_dandelionium.temperature = 1000;
molten_dandelionium.luminosity = 10;
molten_dandelionium.color = Color.fromHex("ffffff").getIntColor();
molten_dandelionium.stillLocation = "base:fluids/molten";
molten_dandelionium.flowingLocation = "base:fluids/molten_flowing";
molten_dandelionium.register();

val molten_myosotisium = mods.contenttweaker.VanillaFactory.createFluid("myosotisium", Color.fromHex("6531cb").getIntColor());
molten_myosotisium.material = <blockmaterial:lava>;
molten_myosotisium.viscosity = 3000;
molten_myosotisium.density = 6500;
molten_myosotisium.colorize = true;
molten_myosotisium.temperature = 1000;
molten_myosotisium.luminosity = 10;
molten_myosotisium.color = Color.fromHex("6531cb").getIntColor();
molten_myosotisium.stillLocation = "base:fluids/molten";
molten_myosotisium.flowingLocation = "base:fluids/molten_flowing";
molten_myosotisium.register();

val molten_begonium = mods.contenttweaker.VanillaFactory.createFluid("begonium", Color.fromHex("ff7ef1").getIntColor());
molten_begonium.material = <blockmaterial:lava>;
molten_begonium.viscosity = 3000;
molten_begonium.density = 6500;
molten_begonium.colorize = true;
molten_begonium.temperature = 1000;
molten_begonium.luminosity = 10;
molten_begonium.color = Color.fromHex("ff7ef1").getIntColor();
molten_begonium.stillLocation = "base:fluids/molten";
molten_begonium.flowingLocation = "base:fluids/molten_flowing";
molten_begonium.register();

val molten_carnationium = mods.contenttweaker.VanillaFactory.createFluid("carnationium", Color.fromHex("c7b9d7").getIntColor());
molten_carnationium.material = <blockmaterial:lava>;
molten_carnationium.viscosity = 3000;
molten_carnationium.density = 6500;
molten_carnationium.colorize = true;
molten_carnationium.temperature = 1000;
molten_carnationium.luminosity = 10;
molten_carnationium.color = Color.fromHex("c7b9d7").getIntColor();
molten_carnationium.stillLocation = "base:fluids/molten";
molten_carnationium.flowingLocation = "base:fluids/molten_flowing";
molten_carnationium.register();

val molten_botanical_awakened = mods.contenttweaker.VanillaFactory.createFluid("botanical_awakened", Color.fromHex("53756b").getIntColor());
molten_botanical_awakened.material = <blockmaterial:lava>;
molten_botanical_awakened.viscosity = 3000;
molten_botanical_awakened.density = 6500;
molten_botanical_awakened.colorize = true;
molten_botanical_awakened.temperature = 1000;
molten_botanical_awakened.luminosity = 10;
molten_botanical_awakened.color = Color.fromHex("53756b").getIntColor();
molten_botanical_awakened.stillLocation = "base:fluids/molten";
molten_botanical_awakened.flowingLocation = "base:fluids/molten_flowing";
molten_botanical_awakened.register();

val molten_star_alloy = mods.contenttweaker.VanillaFactory.createFluid("star_alloy", Color.fromHex("b9b4a0").getIntColor());
molten_star_alloy.material = <blockmaterial:lava>;
molten_star_alloy.viscosity = 3000;
molten_star_alloy.density = 6500;
molten_star_alloy.colorize = true;
molten_star_alloy.temperature = 1000;
molten_star_alloy.luminosity = 10;
molten_star_alloy.color = Color.fromHex("b9b4a0").getIntColor();
molten_star_alloy.stillLocation = "base:fluids/molten";
molten_star_alloy.flowingLocation = "base:fluids/molten_flowing";
molten_star_alloy.register();



//液化类
val liquid_air = mods.contenttweaker.VanillaFactory.createFluid("liquid_air", Color.fromHex("ffffff").getIntColor());
liquid_air.material = <blockmaterial:water>;
liquid_air.viscosity = 3000;
liquid_air.density = -1000;
liquid_air.colorize = true;
liquid_air.temperature = 100;
liquid_air.luminosity = 0;
liquid_air.color = Color.fromHex("ffffff").getIntColor();
liquid_air.stillLocation = "base:fluids/liquid";
liquid_air.flowingLocation = "base:fluids/liquid_flow";
liquid_air.register();

val hydrochloric_acid = mods.contenttweaker.VanillaFactory.createFluid("hydrochloric_acid", Color.fromHex("869ca7").getIntColor());
hydrochloric_acid.material = <blockmaterial:water>;
hydrochloric_acid.viscosity = 3000;
hydrochloric_acid.density = 1000;
hydrochloric_acid.colorize = true;
hydrochloric_acid.temperature = 100;
hydrochloric_acid.luminosity = 0;
hydrochloric_acid.color = Color.fromHex("869ca7").getIntColor();
hydrochloric_acid.stillLocation = "base:fluids/liquid";
hydrochloric_acid.flowingLocation = "base:fluids/liquid_flow";
hydrochloric_acid.register();

val nitric_acid = mods.contenttweaker.VanillaFactory.createFluid("nitric_acid", Color.fromHex("2005aa").getIntColor());
nitric_acid.material = <blockmaterial:water>;
nitric_acid.viscosity = 3000;
nitric_acid.density = 1000;
nitric_acid.colorize = true;
nitric_acid.temperature = 400;
nitric_acid.luminosity = 0;
nitric_acid.color = Color.fromHex("2005aa").getIntColor();
nitric_acid.stillLocation = "base:fluids/liquid";
nitric_acid.flowingLocation = "base:fluids/liquid_flow";
nitric_acid.register();

val nitrogen_oxide = mods.contenttweaker.VanillaFactory.createFluid("nitrogen_oxide", Color.fromHex("7d99b6").getIntColor());
nitrogen_oxide.material = <blockmaterial:water>;
nitrogen_oxide.viscosity = 3000;
nitrogen_oxide.density = -1000;
nitrogen_oxide.colorize = true;
nitrogen_oxide.temperature = 400;
nitrogen_oxide.luminosity = 0;
nitrogen_oxide.color = Color.fromHex("7d99b6").getIntColor();
nitrogen_oxide.stillLocation = "base:fluids/liquid";
nitrogen_oxide.flowingLocation = "base:fluids/liquid_flow";
nitrogen_oxide.register();

val nitrogen_dioxide = mods.contenttweaker.VanillaFactory.createFluid("nitrogen_dioxide", Color.fromHex("8398ae").getIntColor());
nitrogen_dioxide.material = <blockmaterial:water>;
nitrogen_dioxide.viscosity = 3000;
nitrogen_dioxide.density = -1000;
nitrogen_dioxide.colorize = true;
nitrogen_dioxide.temperature = 400;
nitrogen_dioxide.luminosity = 0;
nitrogen_dioxide.color = Color.fromHex("8398ae").getIntColor();
nitrogen_dioxide.stillLocation = "base:fluids/liquid";
nitrogen_dioxide.flowingLocation = "base:fluids/liquid_flow";
nitrogen_dioxide.register();

val liquid_pe = mods.contenttweaker.VanillaFactory.createFluid("pe", Color.fromHex("ffffff").getIntColor());
liquid_pe.material = <blockmaterial:water>;
liquid_pe.viscosity = 3000;
liquid_pe.density = 1000;
liquid_pe.colorize = true;
liquid_pe.temperature = 400;
liquid_pe.luminosity = 10;
liquid_pe.color = Color.fromHex("ffffff").getIntColor();
liquid_pe.stillLocation = "base:fluids/liquid";
liquid_pe.flowingLocation = "base:fluids/liquid_flow";
liquid_pe.register();
