/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#priority 50
#no_fix_recipe_book

import crafttweaker.item.IItemStack;
import crafttweaker.data.IData;
import crafttweaker.item.IIngredient;

import mods.zenstages.ZenStager;
import mods.zenstages.Stage;
import mods.ItemStages;
import mods.jei.JEI;

import scripts.util.recipes as RecipeUtil;
import scripts.util.lang as LangUtil;

val disabledItems as IIngredient[] = [
    <extrautils2:user>,
    <openblocks:block_placer>,
    <cyclicmagic:placer_block>,
    <actuallyadditions:block_placer>,
    <betternether:stalagnate_bowl>,
    <betternether:stalagnate_bowl_apple>,
    <betternether:stalagnate_bowl_mushroom>,
    <betternether:stalagnate_bowl_wart>,
    <botania:blackholetalisman>,
    <extrautils2:wateringcan:*>,
    <bountifulbaubles:trinketbrokenheart:*>,
    <actuallyadditions:block_greenhouse_glass>,
    <extrautils2:lawsword:*>,
    <extrautils2:lawsword:*>.withTag({ench:[]}),
    <openblocks:sprinkler>,
    <astralsorcery:itemenchantmentamulet>,
    <lootbags:loot_recycler>,
    <lootbags:loot_storage>,
    <bloodarsenal:base_item:9>,
    <tconstruct:spaghetti:*>,
    <tconstruct:moms_spaghetti>,
    <abyssalcraft:abyssalniteu>,
    <abyssalcraft:coraliumu>,
    <abyssalcraft:dreadiumu>,
    <abyssalcraft:ethaxiumu>,
    <twilightforest:uncrafting_table>,
    <cyclicmagic:spikes_diamond>,
	<extrautils2:spike_diamond>,
    <thaumadditions:thaumic_lectern>,
    <cyclicmagic:cyclic_wand_build:*>,
    <draconicevolution:wyvern_sword:*>,
    <draconicevolution:wyvern_sword:*>,
    <draconicevolution:wyvern_shovel:*>,
    <draconicevolution:wyvern_bow:*>,
    <draconicevolution:wyvern_axe:*>,
    <draconicevolution:wyvern_pick:*>,
    <draconicevolution:wyvern_helm:*>,
    <draconicevolution:wyvern_chest:*>,
    <draconicevolution:wyvern_legs:*>,
    <draconicevolution:wyvern_boots:*>,
    <draconicevolution:draconic_sword:*>,
    <draconicevolution:draconic_shovel:*>,
    <draconicevolution:draconic_bow:*>,
    <draconicevolution:draconic_axe:*>,
    <draconicevolution:draconic_pick:*>,
    <draconicevolution:draconic_helm:*>,
    <draconicevolution:draconic_chest:*>,
    <draconicevolution:draconic_legs:*>,
    <draconicevolution:draconic_boots:*>,
    <draconicadditions:chaotic_helm:*>,
    <draconicadditions:chaotic_chest:*>,
    <draconicadditions:chaotic_legs:*>,
    <draconicadditions:chaotic_boots:*>,
    <draconicevolution:wyvern_sword:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_shovel:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_bow:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_axe:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_pick:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_helm:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_chest:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_legs:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:wyvern_boots:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_sword:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_shovel:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_bow:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_axe:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_pick:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_helm:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_chest:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_legs:*>.withTag({DEUpgrades: {}}),
    <draconicevolution:draconic_boots:*>.withTag({DEUpgrades: {}}),
    <draconicadditions:chaotic_helm:*>.withTag({DEUpgrades: {}}),
    <draconicadditions:chaotic_chest:*>.withTag({DEUpgrades: {}}),
    <draconicadditions:chaotic_legs:*>.withTag({DEUpgrades: {}}),
    <draconicadditions:chaotic_boots:*>.withTag({DEUpgrades: {}}),
    <cyclicmagic:sprinkler>,
    <cyclicmagic:bundled_pipe>,
    <enderio:block_powered_spawner>,
    <enderio:item_broken_spawner>,
    <bloodmagic:bound_pickaxe:*>,
    <bloodmagic:bound_axe:*>,
    <bloodarsenal:bound_sickle:*>,
    <bloodmagic:bound_shovel:*>,
    <bloodmagic:bound_sword:*>,
    <bloodmagic:living_armour_helmet:*>,
    <bloodmagic:living_armour_chest:*>,
    <bloodmagic:living_armour_chest:*>.withTag({}),
    <bloodmagic:living_armour_leggings:*>,
    <bloodmagic:living_armour_boots:*>,
    <cyclicmagic:magnet_anti_block>,
    <bloodmagic:bound_sword:*>.withTag({activated: 0 as byte}),
    <bloodmagic:bound_sword:*>.withTag({activated: 1 as byte}),
    <bloodmagic:bound_sword:*>,
    <bloodmagic:bound_pickaxe:*>.withTag({activated: 0 as byte}),
    <bloodmagic:bound_pickaxe:*>.withTag({activated: 1 as byte}),
    <bloodmagic:bound_pickaxe:*>,
    <bloodmagic:bound_axe:*>.withTag({activated: 0 as byte}),
    <bloodmagic:bound_axe:*>.withTag({activated: 1 as byte}),
    <bloodmagic:bound_axe:*>,
    <bloodmagic:bound_shovel:*>.withTag({activated: 0 as byte}),
    <bloodmagic:bound_shovel:*>.withTag({activated: 1 as byte}),
    <bloodmagic:bound_shovel:*>,
    <animus:kama_bound:*>,
    <cyclicmagic:tool_push:*>,
    <cyclicmagic:tool_push:*>.withTag({}),
    <darkutils:trap_tile:6>,
    <thermalexpansion:augment:401>,
    <appliedenergistics2:nether_quartz_pickaxe:*>,
    <appliedenergistics2:certus_quartz_pickaxe:*>,
    <candymod:cotton_candy_pickaxe:*>,
    <betternether:cincinnasite_pickaxe_diamond:*>,
    <bloodarsenal:stasis_pickaxe:*>,
    <enderio:item_stellar_alloy_pickaxe:*>,
    <enderio:item_stellar_alloy_sword:*>,
    <enderio:item_stellar_alloy_leggings:*>,
    <enderio:item_stellar_alloy_chestplate:*>,
    <enderio:item_stellar_alloy_helmet:*>,
    <enderio:item_stellar_alloy_boots:*>,
    <enderio:item_end_steel_shield:*>,
    <enderio:item_dark_steel_shield:*>,
    <enderio:item_dark_steel_helmet:*>,
    <enderio:item_dark_steel_chestplate:*>,
    <enderio:item_dark_steel_leggings:*>,
    <enderio:item_dark_steel_boots:*>,
    <enderio:item_dark_steel_pickaxe:*>,
    <enderio:item_dark_steel_sword:*>,
    <enderio:item_dark_steel_axe:*>,
    <enderio:item_dark_steel_bow:*>,
    <enderio:item_dark_steel_shears:*>,
    <enderio:item_dark_steel_crook:*>,
    <enderio:item_dark_steel_hand:*>,
    <enderio:item_end_steel_sword:*>,
    <enderio:item_end_steel_pickaxe:*>,
    <enderio:item_end_steel_axe:*>,
    <enderio:item_end_steel_bow:*>,
    <enderio:item_end_steel_helmet:*>,
    <enderio:item_end_steel_chestplate:*>,
    <enderio:item_end_steel_leggings:*>,
    <enderio:item_end_steel_boots:*>,
    <candymod:cotton_candy_sword:*>,
    <appliedenergistics2:certus_quartz_sword:*>,
    <appliedenergistics2:nether_quartz_sword:*>,
    <thaumcraft:thaumium_sword:*>,
    <thaumcraft:void_sword:*>,
    <natura:netherquartz_sword:*>,
    <natura:fusewood_sword:*>,
    <natura:darkwood_sword:*>,
    <natura:bloodwood_sword:*>,
    <thaumcraft:void_axe:*>,
    <thaumcraft:thaumium_axe:*>,
    <sakura:sakura_axe:*>,
    <sakura:sakura_pickaxe:*>,
    <natura:netherquartz_axe:*>,
    <natura:darkwood_axe:*>,
    <natura:fusewood_axe:*>,
    <natura:bloodwood_axe:*>,
    <natura:ghostwood_axe:*>,
    <cyclicmagic:crystal_axe:*>,
    <extrautils2:fireaxe:*>,
    <bloodarsenal:stasis_axe:*>,
    <betternether:cincinnasite_axe_diamond:*>,
    <appliedenergistics2:nether_quartz_axe:*>,
    <appliedenergistics2:certus_quartz_axe:*>,
    <tofucraft:sworddiamond:*>,
    <tofucraft:swordmetal:*>,
    <tofucraft:swordsolid:*>,
    <tofucraft:swordmomen:*>,
    <tofucraft:swordkinu:*>,
    <cyclicmagic:crystal_sword:*>,
    <cyclicmagic:sword_ender:*>,
    <cyclicmagic:sword_weakness:*>,
    <cyclicmagic:sword_slowness:*>,
    <cyclicmagic:sandstone_sword:*>,
    <natura:ghostwood_sword:*>,
    <sakura:sakura_shovel:*>,
    <thaumcraft:thaumium_shovel:*>,
    <thaumcraft:void_shovel:*>,
    <natura:netherquartz_shovel:*>,
    <natura:fusewood_shovel:*>,
    <natura:darkwood_shovel:*>,
    <natura:bloodwood_shovel:*>,
    <natura:ghostwood_shovel:*>,
    <forestry:bronze_shovel:*>,
    <forestry:bronze_pickaxe:*>,
    <forestry:kit_pickaxe>,
    <appliedenergistics2:certus_quartz_hoe:*>,
    <appliedenergistics2:nether_quartz_hoe:*>,
    <sakura:sakura_hoe:*>,
    <cyclicmagic:sandstone_hoe:*>,
    <cyclicmagic:netherbrick_hoe:*>,
    <cyclicmagic:crystal_hoe:*>,
    <bloodarsenal:stasis_shovel:*>,
    <candymod:cotton_candy_shovel:*>,
    <draconicevolution:draconic_spawner>,
    <enderio:item_material:9>,
    <enderio:item_material:10>,
    <inventorypets:solstice_sword>,
    <inventorypets:solstice_helmet>,
    <inventorypets:solstice_chestplate>,
    <inventorypets:solstice_leggings>,
    <inventorypets:solstice_boots>,
    <inventorypets:solstice_sword>.withTag({ench: [{lvl: 3 as short, id: 34}, {lvl: 2 as short, id: 16}, {lvl: 2 as short, id: 17}]}),
    <inventorypets:solstice_helmet>.withTag({ench: [{lvl: 4 as short, id: 34}, {lvl: 3 as short, id: 5}, {lvl: 1 as short, id: 6}]}),
    <inventorypets:solstice_chestplate>.withTag({ench: [{lvl: 4 as short, id: 1}, {lvl: 4 as short, id: 4}, {lvl: 3 as short, id: 7}]}),
    <inventorypets:solstice_leggings>.withTag({ench: [{lvl: 4 as short, id: 34}, {lvl: 4 as short, id: 3}, {lvl: 4 as short, id: 0}]}),
    <inventorypets:solstice_boots>.withTag({ench: [{lvl: 4 as short, id: 34}, {lvl: 4 as short, id: 1}, {lvl: 4 as short, id: 2}]}),
    <extrabotany:goblinslayerhelm>,
    <extrabotany:goblinslayerchest>,
    <extrabotany:goblinslayerlegs>,
    <extrabotany:goblinslayerboots>,
    <extrabotany:goblinslayerhelm>.withTag({isday: 0 as byte}),
    <extrabotany:goblinslayerchest>.withTag({isday: 0 as byte}),
    <extrabotany:goblinslayerlegs>.withTag({isday: 0 as byte}),
    <extrabotany:goblinslayerboots>.withTag({isday: 0 as byte}),
    <cyclicmagic:auto_crafter>,
    <cyclicmagic:auto_packager>,
    <extrautils2:chunkloader>,
    <botania:unholycloak>,
    <botania:balancecloak>,
    <botania:holycloak>,
    <abyssalcraft:dhelmet>,
    <abyssalcraft:dplate>,
    <abyssalcraft:dlegs>,
    <abyssalcraft:dboots>,
    <extrautils2:goldenlasso>,
    <extrautils2:goldenlasso:1>,
    <extrautils2:spike_gold>,
    <forge:bucketfilled>.withTag({FluidName: "hot_spring_water", Amount: 1000}),
    <forge:bucketfilled>.withTag({FluidName: "sakura.hot_spring_water", Amount: 1000}),
    <thermalexpansion:florb>.withTag({Fluid: "hot_spring_water"}),
    <thermalexpansion:florb>.withTag({Fluid: "sakura.hot_spring_water"}),
    <forestry:can:*>.withTag({Fluid: {FluidName: "hot_spring_water", Amount: 1000}}),
    <forestry:can:*>.withTag({Fluid: {FluidName: "sakura.hot_spring_water", Amount: 1000}}),
    <forestry:capsule:*>.withTag({Fluid: {FluidName: "hot_spring_water", Amount: 1000}}),
    <forestry:capsule:*>.withTag({Fluid: {FluidName: "sakura.hot_spring_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({Fluid: {FluidName: "hot_spring_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({Fluid: {FluidName: "sakura.hot_spring_water", Amount: 1000}}),
    <liquid:hot_spring_water>,
    <liquid:sakura.hot_spring_water>,
    <mekanism:cardboardbox>,
    <cyclicmagic:block_fishing>,
    <extrautils2:playerchest>,
    <harvestcraft:hardenedleatherhelmitem>,
    <harvestcraft:hardenedleatherchestitem>,
    <harvestcraft:hardenedleatherleggingsitem>,
    <harvestcraft:hardenedleatherbootsitem>,
    <projecte:item.pe_void_ring>.withTag({teleportCooldown: 0 as byte}),
    <projecte:item.pe_void_ring>,
    <botanicadds:mana_stealer_sword>,
    <botanicadds:terra_protector>,
    <jaopca:item_mysticalseedsastralstarmetal>,
    <mekanism:armoredjetpack>.withTag({mekData: {stored: {amount: 24000, gasName: "hydrogen"}}}),
    <mekanism:armoredjetpack>,
    <mekanism:jetpack>.withTag({mekData: {stored: {amount: 24000, gasName: "hydrogen"}}}),
    <mekanism:jetpack>,
    <natura:blaze_rail_detector>,
    <natura:blaze_rail>,
    <natura:blaze_rail_golden>,
    <natura:blaze_rail_activator>,
    <twilightforest:twilight_sapling:5>,
    <sakura:samurai_helmet>,
    <sakura:samurai_chest>,
    <sakura:samurai_pants>,
    <sakura:samurai_shoes>,
    <inventorypets:item_petrifier>,
    <cyclicmagic:fluid_pipe>,
    <cyclicmagic:fluid_pump>,
    <cyclicmagic:energy_pipe>,
    <cyclicmagic:item_pipe>,
    <cyclicmagic:item_pump>,
    <cyclicmagic:energy_pump>,
    <tiths:block_cloud>,
    <tiths:ingot_titanium>,
    <tiths:nugget_titanium>,
    <tiths:ore_rutile>,
    <tiths:block_titanium>,
    <ageofminecraft:ozelot>,
    <ageofminecraft:endermite>,
    <ageofminecraft:silverfish>,
    <ageofminecraft:villager>,
    <ageofminecraft:skeleton>,
    <ageofminecraft:spider>,
    <ageofminecraft:vex>,
    <ageofminecraft:zombie>,
    <ageofminecraft:cavespider>,
    <ageofminecraft:enderman>,
    <ageofminecraft:husk>,
    <ageofminecraft:shulker>,
    <ageofminecraft:stray>,
    <ageofminecraft:vindicator>,
    <ageofminecraft:irongolem>,
    <ageofminecraft:evoker>,
    <buildinggadgets:exchangertool>,
    <avaritia:neutronium_compressor>,
    <divinerpg:healing_stone>,
    <divinerpg:liopleurodon_teeth>,
    <divinerpg:liopleurodon_skull>,
    <divinerpg:shark_fin>,
    <divinerpg:whale_fin>,
    <divinerpg:eden_arrow>,
    <divinerpg:fury_arrow>,
    <divinerpg:wildwood_arrow>,
    <divinerpg:teaker_arrow>,
    <divinerpg:darven_arrow>,
    <divinerpg:pardimal_arrow>,
    <divinerpg:karos_arrow>,
    <divinerpg:ever_arrow>,
    <divinerpg:angelic_helmet>,
    <divinerpg:angelic_chestplate>,
    <divinerpg:angelic_leggings>,
    <divinerpg:angelic_boots>,
    <divinerpg:aquastrive_helmet>,
    <divinerpg:aquastrive_chestplate>,
    <divinerpg:aquastrive_leggings>,
    <divinerpg:aquastrive_boots>,
    <divinerpg:arlemite_helmet>,
    <divinerpg:arlemite_chestplate>,
    <divinerpg:arlemite_leggings>,
    <divinerpg:arlemite_boots>,
    <divinerpg:bedrock_helmet>,
    <divinerpg:bedrock_chestplate>,
    <divinerpg:bedrock_leggings>,
    <divinerpg:bedrock_boots>,
    <divinerpg:corrupted_helmet>,
    <divinerpg:corrupted_chestplate>,
    <divinerpg:corrupted_leggings>,
    <divinerpg:corrupted_boots>,
    <divinerpg:divine_helmet>,
    <divinerpg:divine_chestplate>,
    <divinerpg:divine_leggings>,
    <divinerpg:divine_boots>,
    <divinerpg:elite_realmite_helmet>,
    <divinerpg:elite_realmite_chestplate>,
    <divinerpg:elite_realmite_leggings>,
    <divinerpg:elite_realmite_boots>,
    <divinerpg:ender_helmet>,
    <divinerpg:ender_chestplate>,
    <divinerpg:ender_leggings>,
    <divinerpg:ender_boots>,
    <divinerpg:blue_ender_helmet>,
    <divinerpg:blue_ender_chestplate>,
    <divinerpg:blue_ender_leggings>,
    <divinerpg:blue_ender_boots>,
    <divinerpg:gray_ender_helmet>,
    <divinerpg:gray_ender_chestplate>,
    <divinerpg:gray_ender_leggings>,
    <divinerpg:gray_ender_boots>,
    <divinerpg:green_ender_helmet>,
    <divinerpg:green_ender_chestplate>,
    <divinerpg:green_ender_leggings>,
    <divinerpg:green_ender_boots>,
    <divinerpg:red_ender_helmet>,
    <divinerpg:red_ender_chestplate>,
    <divinerpg:red_ender_leggings>,
    <divinerpg:red_ender_boots>,
    <divinerpg:yellow_ender_helmet>,
    <divinerpg:yellow_ender_chestplate>,
    <divinerpg:yellow_ender_leggings>,
    <divinerpg:yellow_ender_boots>,
    <divinerpg:frozen_helmet>,
    <divinerpg:frozen_chestplate>,
    <divinerpg:frozen_leggings>,
    <divinerpg:frozen_boots>,
    <divinerpg:inferno_helmet>,
    <divinerpg:inferno_chestplate>,
    <divinerpg:inferno_leggings>,
    <divinerpg:inferno_boots>,
    <divinerpg:jack_o_man_helmet>,
    <divinerpg:jack_o_man_chestplate>,
    <divinerpg:jack_o_man_leggings>,
    <divinerpg:jack_o_man_boots>,
    <divinerpg:jungle_helmet>,
    <divinerpg:jungle_chestplate>,
    <divinerpg:jungle_leggings>,
    <divinerpg:jungle_boots>,
    <divinerpg:kraken_helmet>,
    <divinerpg:kraken_chestplate>,
    <divinerpg:kraken_leggings>,
    <divinerpg:kraken_boots>,
    <divinerpg:netherite_helmet>,
    <divinerpg:netherite_chestplate>,
    <divinerpg:netherite_leggings>,
    <divinerpg:netherite_boots>,
    <divinerpg:realmite_helmet>,
    <divinerpg:realmite_chestplate>,
    <divinerpg:realmite_leggings>,
    <divinerpg:realmite_boots>,
    <divinerpg:rupee_helmet>,
    <divinerpg:rupee_chestplate>,
    <divinerpg:rupee_leggings>,
    <divinerpg:rupee_boots>,
    <divinerpg:blue_rupee_helmet>,
    <divinerpg:blue_rupee_chestplate>,
    <divinerpg:blue_rupee_leggings>,
    <divinerpg:blue_rupee_boots>,
    <divinerpg:gray_rupee_helmet>,
    <divinerpg:gray_rupee_chestplate>,
    <divinerpg:gray_rupee_leggings>,
    <divinerpg:gray_rupee_boots>,
    <divinerpg:green_rupee_helmet>,
    <divinerpg:green_rupee_chestplate>,
    <divinerpg:green_rupee_leggings>,
    <divinerpg:green_rupee_boots>,
    <divinerpg:red_rupee_helmet>,
    <divinerpg:red_rupee_chestplate>,
    <divinerpg:red_rupee_leggings>,
    <divinerpg:red_rupee_boots>,
    <divinerpg:yellow_rupee_helmet>,
    <divinerpg:yellow_rupee_chestplate>,
    <divinerpg:yellow_rupee_leggings>,
    <divinerpg:yellow_rupee_boots>,
    <divinerpg:shadow_helmet>,
    <divinerpg:shadow_chestplate>,
    <divinerpg:shadow_leggings>,
    <divinerpg:shadow_boots>,
    <divinerpg:skeleman_helmet>,
    <divinerpg:skeleman_chestplate>,
    <divinerpg:skeleman_leggings>,
    <divinerpg:skeleman_boots>,
    <divinerpg:terran_helmet>,
    <divinerpg:terran_chestplate>,
    <divinerpg:terran_leggings>,
    <divinerpg:terran_boots>,
    <divinerpg:wither_reaper_helmet>,
    <divinerpg:wither_reaper_chestplate>,
    <divinerpg:wither_reaper_leggings>,
    <divinerpg:wither_reaper_boots>,
    <divinerpg:santa_helmet>,
    <divinerpg:santa_chestplate>,
    <divinerpg:santa_leggings>,
    <divinerpg:santa_boots>,
    <divinerpg:eden_helmet>,
    <divinerpg:eden_chestplate>,
    <divinerpg:eden_leggings>,
    <divinerpg:eden_boots>,
    <divinerpg:wildwood_helmet>,
    <divinerpg:wildwood_chestplate>,
    <divinerpg:wildwood_leggings>,
    <divinerpg:wildwood_boots>,
    <divinerpg:apalachia_helmet>,
    <divinerpg:apalachia_chestplate>,
    <divinerpg:apalachia_leggings>,
    <divinerpg:apalachia_boots>,
    <divinerpg:skythern_helmet>,
    <divinerpg:skythern_chestplate>,
    <divinerpg:skythern_leggings>,
    <divinerpg:skythern_boots>,
    <divinerpg:mortum_helmet>,
    <divinerpg:mortum_chestplate>,
    <divinerpg:mortum_leggings>,
    <divinerpg:mortum_boots>,
    <divinerpg:halite_helmet>,
    <divinerpg:halite_chestplate>,
    <divinerpg:halite_leggings>,
    <divinerpg:halite_boots>,
    <divinerpg:awakened_halite_helmet>,
    <divinerpg:awakened_halite_chestplate>,
    <divinerpg:awakened_halite_leggings>,
    <divinerpg:awakened_halite_boots>,
    <divinerpg:korma_helmet>,
    <divinerpg:korma_chestplate>,
    <divinerpg:korma_leggings>,
    <divinerpg:korma_boots>,
    <divinerpg:vemos_helmet>,
    <divinerpg:vemos_chestplate>,
    <divinerpg:vemos_leggings>,
    <divinerpg:vemos_boots>,
    <divinerpg:degraded_helmet>,
    <divinerpg:degraded_hood>,
    <divinerpg:degraded_mask>,
    <divinerpg:degraded_chestplate>,
    <divinerpg:degraded_leggings>,
    <divinerpg:degraded_boots>,
    <divinerpg:finished_helmet>,
    <divinerpg:finished_hood>,
    <divinerpg:finished_mask>,
    <divinerpg:finished_chestplate>,
    <divinerpg:finished_leggings>,
    <divinerpg:finished_boots>,
    <divinerpg:glistening_helmet>,
    <divinerpg:glistening_hood>,
    <divinerpg:glistening_mask>,
    <divinerpg:glistening_chestplate>,
    <divinerpg:glistening_leggings>,
    <divinerpg:glistening_boots>,
    <divinerpg:demonized_helmet>,
    <divinerpg:demonized_hood>,
    <divinerpg:demonized_mask>,
    <divinerpg:demonized_chestplate>,
    <divinerpg:demonized_leggings>,
    <divinerpg:demonized_boots>,
    <divinerpg:tormented_helmet>,
    <divinerpg:tormented_hood>,
    <divinerpg:tormented_mask>,
    <divinerpg:tormented_chestplate>,
    <divinerpg:tormented_leggings>,
    <divinerpg:tormented_boots>,
    <divinerpg:yellow_ender_sword>,
    <divinerpg:frost_sword>,
    <divinerpg:flaming_fury>,
    <divinerpg:fury_maul>,
    <divinerpg:inferno_sword>,
    <divinerpg:jungle_knife>,
    <divinerpg:jungle_rapier>,
    <divinerpg:molten_sword>,
    <divinerpg:ocean_knife>,
    <divinerpg:bedrock_maul>,
    <divinerpg:bedrock_sword>,
    <divinerpg:arlemite_stabber>,
    <divinerpg:aquatooth_sword>,
    <divinerpg:aquatooth_maul>,
    <divinerpg:aquaton>,
    <divinerpg:aquatic_trident>,
    <divinerpg:aquatic_maul>,
    <divinerpg:aquatic_dagger>,
    <divinerpg:gray_divine_sword>,
    <divinerpg:divine_sword>,
    <divinerpg:blue_divine_sword>,
    <divinerpg:death_bringer>,
    <divinerpg:cyclopsian_sword>,
    <divinerpg:crabclaw_maul>,
    <divinerpg:corrupted_maul>,
    <divinerpg:bluefire_sword>,
    <divinerpg:bloodgem_sword>,
    <divinerpg:red_ender_sword>,
    <divinerpg:green_ender_sword>,
    <divinerpg:ender_sword>,
    <divinerpg:blue_ender_sword>,
    <divinerpg:black_ender_sword>,
    <divinerpg:dual_claw>,
    <divinerpg:yellow_divine_sword>,
    <divinerpg:red_divine_sword>,
    <divinerpg:green_divine_sword>,
    <divinerpg:arcanium_saber>,
    <divinerpg:ender_scepter>,
    <divinerpg:livicia_sword>,
    <divinerpg:storm_sword>,
    <divinerpg:shadow_saber>,
    <divinerpg:terran_knife>,
    <divinerpg:terran_dagger>,
    <divinerpg:slime_sword>,
    <divinerpg:shark_sword>,
    <divinerpg:scorching_sword>,
    <divinerpg:sandslash>,
    <divinerpg:rupee_rapier>,
    <divinerpg:realmite_sword>,
    <divinerpg:poison_saber>,
    <divinerpg:snowslash>,
    <divinerpg:icine_sword>,
    <divinerpg:glacier_sword>,
    <divinerpg:frozen_maul>,
    <divinerpg:frostking_sword>,
    <divinerpg:enderice>,
    <divinerpg:palavence>,
    <divinerpg:massivence>,
    <divinerpg:terran_maul>,
    <divinerpg:arcanite_blade>,
    <divinerpg:halite_blade>,
    <divinerpg:mortum_blade>,
    <divinerpg:skythern_blade>,
    <divinerpg:apalachia_blade>,
    <divinerpg:wildwood_blade>,
    <divinerpg:eden_blade>,
    <divinerpg:frossivence>,
    <divinerpg:icicle_bane>,
    <divinerpg:eden_axe>,
    <divinerpg:wildwood_shovel>,
    <divinerpg:wildwood_pickaxe>,
    <divinerpg:wildwood_axe>,
    <divinerpg:apalachia_shovel>,
    <divinerpg:apalachia_pickaxe>,
    <divinerpg:apalachia_axe>,
    <divinerpg:skythern_shovel>,
    <divinerpg:skythern_pickaxe>,
    <divinerpg:bedrock_axe>,
    <divinerpg:bedrock_pickaxe>,
    <divinerpg:bedrock_shovel>,
    <divinerpg:arlemite_shickaxe>,
    <divinerpg:arlemite_hoe>,
    <divinerpg:arlemite_axe>,
    <divinerpg:arlemite_pickaxe>,
    <divinerpg:arlemite_shovel>,
    <divinerpg:staff_of_enrichment>,
    <divinerpg:realmite_pickaxe>,
    <divinerpg:realmite_shovel>,
    <divinerpg:divine_shickaxe>,
    <divinerpg:divine_axe>,
    <divinerpg:divine_pickaxe>,
    <divinerpg:divine_shovel>,
    <divinerpg:corrupted_axe>,
    <divinerpg:corrupted_pickaxe>,
    <divinerpg:corrupted_shovel>,
    <divinerpg:eden_pickaxe>,
    <divinerpg:eden_shovel>,
    <divinerpg:rupee_shickaxe>,
    <divinerpg:rupee_hoe>,
    <divinerpg:rupee_axe>,
    <divinerpg:rupee_pickaxe>,
    <divinerpg:rupee_shovel>,
    <divinerpg:realmite_hoe>,
    <divinerpg:realmite_axe>,
    <divinerpg:skythern_axe>,
    <divinerpg:mortum_shovel>,
    <divinerpg:mortum_pickaxe>,
    <divinerpg:mortum_axe>,
    <divinerpg:dream_shovel>,
    <divinerpg:dream_pickaxe>,
    <divinerpg:dream_axe>,
    <divinerpg:everbright>,
    <divinerpg:teaker_hammer>,
    <divinerpg:darven_claw>,
    <divinerpg:cermile_claw>,
    <divinerpg:pardimal_claw>,
    <divinerpg:quadrotic_claw>,
    <divinerpg:karos_claw>,
    <divinerpg:heliosis_claw>,
    <divinerpg:arksiane_claw>,
    <divinerpg:quadrotic_staff>,
    <divinerpg:pardimal_staff>,
    <divinerpg:cermile_staff>,
    <divinerpg:darven_staff>,
    <divinerpg:amthirmis_staff>,
    <divinerpg:teaker_staff>,
    <divinerpg:karos_rockmaul>,
    <divinerpg:arksiane_staff>,
    <divinerpg:evernight>,
    <divinerpg:heliosis_hammer>,
    <divinerpg:karos_hammer>,
    <divinerpg:quadrotic_hammer>,
    <divinerpg:pardimal_hammer>,
    <divinerpg:cermile_hammer>,
    <divinerpg:darven_hammer>,
    <divinerpg:amthirmis_hammer>,
    <divinerpg:heliosis_staff>,
    <divinerpg:karos_staff>,
    <divinerpg:arksiane_disk>,
    <divinerpg:heliosis_disk>,
    <divinerpg:karos_disk>,
    <divinerpg:quadrotic_disk>,
    <divinerpg:pardimal_disk>,
    <divinerpg:cermile_disk>,
    <divinerpg:darven_disk>,
    <divinerpg:amthirmis_disk>,
    <divinerpg:everlight>,
    <divinerpg:teaker_backsword>,
    <divinerpg:darven_backsword>,
    <divinerpg:amthirmis_backsword>,
    <divinerpg:cermile_backsword>,
    <divinerpg:teaker_disk>,
    <divinerpg:amthirmis_claw>,
    <divinerpg:teaker_claw>,
    <divinerpg:eversight>,
    <divinerpg:arksiane_cannon>,
    <divinerpg:heliosis_cannon>,
    <divinerpg:karos_cannon>,
    <divinerpg:quadrotic_cannon>,
    <divinerpg:pardimal_cannon>,
    <divinerpg:cermile_cannon>,
    <divinerpg:darven_cannon>,
    <divinerpg:amthirmis_cannon>,
    <divinerpg:teaker_cannon>,
    <divinerpg:everfright>,
    <divinerpg:arksiane_bow>,
    <divinerpg:heliosis_bow>,
    <divinerpg:karos_bow>,
    <divinerpg:quadrotic_bow>,
    <divinerpg:pardimal_bow>,
    <divinerpg:cermile_bow>,
    <divinerpg:darven_bow>,
    <divinerpg:amthirmis_bow>,
    <divinerpg:teaker_bow>,
    <divinerpg:arksiane_backsword>,
    <divinerpg:heliosis_backsword>,
    <divinerpg:karos_backsword>,
    <divinerpg:quadrotic_backsword>,
    <divinerpg:pardimal_backsword>,
    <hammermetals:durasteel_ingot>,
    <hammermetals:durasteel_block>,
    <hammermetals:aeonsteel_ingot>,
    <hammermetals:aeonsteel_block>,
    <hammermetals:chromasteel_ingot>,
    <hammermetals:chromasteel_block>,
    <hammermetals:cosmilite_ingot>,
    <hammermetals:cosmilite_block>
] as IIngredient[];

val disabledRecipeRegex as string[] = [
    "^mysticalagriculture:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(sickle)|(fishing_rod)|(scythe))$",
    "^twilightforest:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet))$",
    "^tofucraft:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(leggins)|(chestplate)|(helmet))$",
    "^defiledlands:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet))$",
    "^abyssalcraft:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(plate)|(legs)|(helm)|(pick))$",
    "^netherex:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(plate)|(legs)|(helm)|(pick))$",
    "^candymod:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick))_(.*)$",
    "^aether_legacy:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick))$",
    "^betternether:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick))$",
    "^tcomplement:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick))$",
    "^bloodarsenal:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick))$",
    "^botania:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick)|(chest))$",
    "^extrabotany:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet)|(legs)|(helm)|(pick)|(chest))$",
    "^enderio:(.*)((pickaxe)|(paxel)|(bow)|(hoe)|(sword)|(axe)|(shovel)|(boots)|(leggings)|(chestplate)|(helmet))$",
    "^thermalfoundation:tool.fishing_rod_(.*)$",
    "^jaopca:block_crystalcluster(.*)$",
    "^actuallyadditions:recipes24[3456789]$",
    "^actuallyadditions:recipes2[56789].$",
    "^actuallyadditions:recipes3[012].$",
    "^actuallyadditions:recipes33[01234567]$",
    "^thermalfoundation:((tool)|(armor))(.*)$",
    "^redstonearsenal:((tool)|(armor))(.*)$",
    "^redstonerepository:((tool)|(armor))(.*)$",
    "^hammermetals:((ingot)|(block)|(ore))$"
];

val outputBlacklist as IItemStack[] = [
    <twilightforest:giant_pickaxe>,
    <twilightforest:giant_sword>,
    <abyssalcraft:dspplate>,
    <abyssalcraft:dltpplate>,
    <abyssalcraft:dirtyplate>,
    <ageofminecraft:withered_nether_star>
];

for ingredient in disabledItems {
    ItemStages.removeItemStage(ingredient);
    ItemStages.addItemStage("disabled", ingredient);
    ItemStages.setUnfamiliarName(LangUtil.translate("greedycraft.stage.disabled_item.name"), ingredient);
    for item in ingredient.items {
        RecipeUtil.remove(item);
        JEI.removeAndHide(item);
        item.addTooltip(game.localize("greedycraft.stage.disabled_item.tooltip"));
    }
}

for recipe in recipes.all {
    for regex in disabledRecipeRegex {
        if (recipe.fullResourceDomain.matches(regex)) {
            var isBlacklisted as bool = false;
            for item in outputBlacklist {
                if (recipe.output.definition.id == item.definition.id && recipe.output.metadata == item.metadata) {
                    isBlacklisted = true;
                    break;
                }
            }
            if (!isBlacklisted) {
                RecipeUtil.remove(recipe.output);
                JEI.removeAndHide(recipe.output);
                recipe.output.addTooltip(game.localize("greedycraft.stage.uncraftable_item.tooltip"));
                // Disabled this to fix the problem of zombies holding question marks
                // ItemStages.removeItemStage(recipe.output);
                // ItemStages.addItemStage("disabled", recipe.output);
                // ItemStages.setUnfamiliarName(game.localize("greedycraft.stage.disabled_item.name"), ingredient);
                break;
            }
        }
    }

}

for item in loadedMods["jaopca"].items {
    if(item.definition.id.startsWith("jaopca:block_crystalcluster")) {
        recipes.remove(item);
        val entryName = item.definition.id.substring("jaopca:block_crystalcluster".length());
        val oreName = "jaopca:item_crystalabyss" + entryName;
        val crystalItem = itemUtils.getItem(oreName);
        if(!isNull(crystalItem)) {
            recipes.addShapeless("jaopca_fix_" + entryName, item, [crystalItem, crystalItem, crystalItem, crystalItem, crystalItem, crystalItem, crystalItem, crystalItem, crystalItem]);
        }
        print("Removing broken JAOPCA recipe: " + item.definition.id + " Replacing with " + oreName);
    }
}
